package org.ideoholic.curium.model.caveat.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "h_caveat")
public class Caveat implements java.io.Serializable {

	private Integer id;
	private Integer sid;
	private String court;
	private String caveattitle;
	private String caveatnumber;
	private String courtname;
	private String status;
	private Date dateofdispose;
	private String filetaken;
	private String filetakenby;
	private String filetakenbyname;
	private String filetakenbynumber;
	private String remarks;
	private Date createddate;
	private Date updateddate;
	private Integer branchid;
	private Integer createduserid;
	private Integer updateduserid;
	private Integer assignto;
	private String fileno;
	private String referredby;
	
	public Caveat() {
	}

	public Caveat(Integer sid,Integer assignto, String court,String caveattitle,String courtname, String status, Date dateofdispose, String filetaken,String filetakenby,
			String filetakenbyname,String filetakenbynumber,Date createddate,Date updateddate, Integer branchid,Integer createduserid,
			Integer updateduserid, String remarks, String caveatnumber, String fileno, String referredby){
		this.sid = sid;
		this.assignto = assignto;
		this.court = court;
		this.caveattitle = caveattitle;
		this.courtname = courtname;
		this.status = status;
		this.dateofdispose = dateofdispose;
		this.filetaken = filetaken;
		this.filetakenby = filetakenby;
		this.filetakenbyname = filetakenbyname;
		this.filetakenbynumber = filetakenbynumber;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.branchid = branchid;
		this.createduserid = createduserid;
		this.updateduserid = updateduserid;
		this.remarks = remarks;
		this.caveatnumber = caveatnumber;
		this.fileno = fileno;
		this.referredby = referredby;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCourt() {
		return court;
	}

	public void setCourt(String court) {
		this.court = court;
	}

	public String getCaveattitle() {
		return caveattitle;
	}

	public void setCaveattitle(String caveattitle) {
		this.caveattitle = caveattitle;
	}

	public String getCourtname() {
		return courtname;
	}

	public void setCourtname(String courtname) {
		this.courtname = courtname;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getDateofdispose() {
		return dateofdispose;
	}

	public void setDateofdispose(Date dateofdispose) {
		this.dateofdispose = dateofdispose;
	}

	public String getFiletaken() {
		return filetaken;
	}

	public void setFiletaken(String filetaken) {
		this.filetaken = filetaken;
	}

	public String getFiletakenby() {
		return filetakenby;
	}

	public void setFiletakenby(String filetakenby) {
		this.filetakenby = filetakenby;
	}

	public String getFiletakenbyname() {
		return filetakenbyname;
	}

	public void setFiletakenbyname(String filetakenbyname) {
		this.filetakenbyname = filetakenbyname;
	}

	public String getFiletakenbynumber() {
		return filetakenbynumber;
	}

	public void setFiletakenbynumber(String filetakenbynumber) {
		this.filetakenbynumber = filetakenbynumber;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getCreateddate() {
		return createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Date getUpdateddate() {
		return updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}

	public Integer getCreateduserid() {
		return createduserid;
	}

	public void setCreateduserid(Integer createduserid) {
		this.createduserid = createduserid;
	}

	public Integer getUpdateduserid() {
		return updateduserid;
	}

	public void setUpdateduserid(Integer updateduserid) {
		this.updateduserid = updateduserid;
	}

	public Integer getAssignto() {
		return assignto;
	}

	public void setAssignto(Integer assignto) {
		this.assignto = assignto;
	}

	public String getCaveatnumber() {
		return caveatnumber;
	}

	public void setCaveatnumber(String caveatnumber) {
		this.caveatnumber = caveatnumber;
	}

	public String getFileno() {
		return fileno;
	}

	public void setFileno(String fileno) {
		this.fileno = fileno;
	}

	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getReferredby() {
		return referredby;
	}

	public void setReferredby(String referredby) {
		this.referredby = referredby;
	}

	
}
