package com.model.subjectdetails.dto;

// default package
// Generated 15 Aug, 2016 12:22:36 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "school")
public class Subject implements java.io.Serializable {

	private Integer subid;
	private String subjectname;
	private Integer minmarks;
	private Integer maxmarks;

	public Subject() {
	}

	public Subject(String subjectname, Integer minmarks, Integer maxmarks) {
		this.subjectname = subjectname;
		this.minmarks = minmarks;
		this.maxmarks = maxmarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subid", unique = true, nullable = false)
	public Integer getSubid() {
		return this.subid;
	}

	public void setSubid(Integer subid) {
		this.subid = subid;
	}

	@Column(name = "subjectname", length = 45)
	public String getSubjectname() {
		return this.subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	@Column(name = "minmarks")
	public Integer getMinmarks() {
		return this.minmarks;
	}

	public void setMinmarks(Integer minmarks) {
		this.minmarks = minmarks;
	}

	@Column(name = "maxmarks")
	public Integer getMaxmarks() {
		return this.maxmarks;
	}

	public void setMaxmarks(Integer maxmarks) {
		this.maxmarks = maxmarks;
	}

}
