package com.model.subjectdetails.dto;

// default package
// Generated 15 Aug, 2016 12:22:36 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject")
public class Subject implements java.io.Serializable {

	private Integer subid;
	private String subjectname;
	private Integer minmarks;
	private Integer maxmarks;
	private int branchid;
	private String examname;
	private String examclass;
	private int userid;

	public Subject() {
	}

	public Subject(String subjectname, Integer minmarks, Integer maxmarks,int branchid, String examname, String examclass, int userid) {
		this.subjectname = subjectname;
		this.minmarks = minmarks;
		this.maxmarks = maxmarks;
		this.branchid = branchid;
		this.examname = examname;
		this.examclass = examclass;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subid", unique = true, nullable = false)
	public Integer getSubid() {
		return this.subid;
	}

	public void setSubid(Integer subid) {
		this.subid = subid;
	}

	@Column(name = "subjectname", length = 45)
	public String getSubjectname() {
		return this.subjectname;
	}

	public void setSubjectname(String subjectname) {
		this.subjectname = subjectname;
	}

	@Column(name = "minmarks")
	public Integer getMinmarks() {
		return this.minmarks;
	}

	public void setMinmarks(Integer minmarks) {
		this.minmarks = minmarks;
	}

	@Column(name = "maxmarks")
	public Integer getMaxmarks() {
		return this.maxmarks;
	}

	public void setMaxmarks(Integer maxmarks) {
		this.maxmarks = maxmarks;
	}

	
	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}

	public String getExamname() {
		return examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	public String getExamclass() {
		return examclass;
	}

	public void setExamclass(String examclass) {
		this.examclass = examclass;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
