package com.model.department.dto;

// default package
// Generated 16 Jan, 2015 12:53:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "school")
public class Department implements java.io.Serializable {

	private Integer depid;
	private String departmentname;

	public Department() {
	}

	public Department(String departmentname) {
		this.departmentname = departmentname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "depid", unique = true, nullable = false)
	public Integer getDepid() {
		return this.depid;
	}

	public void setDepid(Integer depid) {
		this.depid = depid;
	}

	@Column(name = "departmentname", length = 100)
	public String getDepartmentname() {
		return this.departmentname;
	}

	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

}
