package org.ideoholic.curium.model.user.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 12 Sep, 2014 6:03:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ideoholic.curium.model.branch.dto.Branch;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "login")
public class Login implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "lid", unique = true, nullable = false)
	private Integer lid;

	@Column(name = "username", nullable = false, length = 45)
	private String username;

	@Column(name = "password", nullable = false, length = 45)
	private String password;

	@Column(name = "usertype", length = 45)
	private String usertype;

	@Column(name = "branchid")
	private Branch branch;

	@Column(name = "userid")
	private Integer userid;

}