package com.model.branch.dto;

import com.util.MarksSheet;

// default package
// Generated 17 Jul, 2018 11:38:25 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable,Comparable<Branch> {

    private Integer idbranch;
    private String centername;
    private String centercode;
    private String districtcode;
    private String state;

    public Branch() {}

    public Branch(String centername, String centercode, String districtcode, String state) {
        this.centername = centername;
        this.centercode = centercode;
        this.districtcode = districtcode;
        this.state = state;
    }

    public Integer getIdbranch() {
        return this.idbranch;
    }

    public void setIdbranch(Integer idbranch) {
        this.idbranch = idbranch;
    }

    public String getCentername() {
        return this.centername;
    }

    
    public void setCentername(String centername) {
        this.centername = centername;
    }

    
    public String getCentercode() {
        return this.centercode;
    }

    
    public void setCentercode(String centercode) {
        this.centercode = centercode;
    }

    
    public String getDistrictcode() {
        return this.districtcode;
    }

    
    public void setDistrictcode(String districtcode) {
        this.districtcode = districtcode;
    }

    public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
    public int compareTo(Branch result) {
       
        Integer centerCode = Integer.parseInt(((Branch) result).getCentercode());
        return Integer.compare(Integer.parseInt(this.centercode), centerCode);
    }
}
