package com.model.branch.dto;

// default package
// Generated 17 Jul, 2018 4:09:57 PM by Hibernate Tools 5.3.0.Beta2

/**
 * District generated by hbm2java
 */
public class Districts implements java.io.Serializable {

    private Integer iddistrict;
    private String districtname;
    private String districtcode;

    public Districts() {}

    public Districts(String districtname, String districtcode) {
        this.districtname = districtname;
        this.districtcode = districtcode;
    }

    public Integer getIddistrict() {
        return this.iddistrict;
    }

    public void setIddistrict(Integer iddistrict) {
        this.iddistrict = iddistrict;
    }

    public String getDistrictname() {
        return this.districtname;
    }

    public void setDistrictname(String districtname) {
        this.districtname = districtname;
    }

    
    public String getDistrictcode() {
        return this.districtcode;
    }

    
    public void setDistrictcode(String districtcode) {
        this.districtcode = districtcode;
    }

}
