package com.model.student.dto;

// default package
// Generated 14 Feb, 2018 12:05:32 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.model.branch.dto.Branch;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", uniqueConstraints = @UniqueConstraint(columnNames = "studentexternalid"))
public class Student implements java.io.Serializable, Comparable<Student>{

	private Integer sid;
	private String name;
	private String qualification;
	private String examlevel;
	private Integer age;
	private String gender;
	private Date dateofbirth;
	private String languageopted;
	private String districtcode;
	private String centercode;
	private Date admissiondate;
	private String admissionnumber;
	private String remarks;
	private Date createddate;
	private Integer archive;
	private String studentpic;
	private String studentexternalid;
	private String guardiandetails;
	private int branchid;
	private String religion;
	private String education;
	private String admittedin;
	private Integer passedout;
	private Integer droppedout;

	public Student() {
	}

	public Student(String name, String studentexternalid) {
		this.name = name;
		this.studentexternalid = studentexternalid;
	}

	public Student(String name, String qualification, String examlevel,
			Integer age, String gender, Date dateofbirth, String languageopted,
			String districtcode, String centercode, 
			Date admissiondate, String admissionnumber, 
			String remarks, String guardiandetails,
			Date createddate, Integer archive, String studentpic,
			String studentexternalid,  int branchid, String religion, String education,
			String admittedin, int passedout, int droppedout) {
		this.name = name;
		this.qualification = qualification;
		this.examlevel = examlevel;
		this.age = age;
		this.gender = gender;
		this.dateofbirth = dateofbirth;
		this.languageopted = languageopted;
		this.districtcode = districtcode;
		this.centercode = centercode;
		this.admissiondate = admissiondate;
		this.admissionnumber = admissionnumber;
		this.remarks = remarks;
		this.createddate = createddate;
		this.archive = archive;
		this.studentpic = studentpic;
		this.studentexternalid = studentexternalid;
		this.guardiandetails = guardiandetails;
		this.branchid = branchid;
		this.religion = religion;
		this.education = education;
		this.admittedin = admittedin;
		this.passedout = passedout;
		this.droppedout = droppedout;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "qualification", length = 45)
	    
	    public String getQualification() {
	        return this.qualification;
	    }

	    
	    public void setQualification(String qualification) {
	        this.qualification = qualification;
	    }

	@Column(name = "examlevel", length = 45)
	    public String getExamlevel() {
	        return this.examlevel;
	    }

	    
	    public void setExamlevel(String examlevel) {
	        this.examlevel = examlevel;
	    }

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 10)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "languageopted", length = 45)
	    public String getLanguageopted() {
	        return this.languageopted;
	    }

	    
	    public void setLanguageopted(String languageopted) {
	        this.languageopted = languageopted;
	    }


	@Column(name = "districtcode", length = 5)
	    public String getDistrictcode() {
	        return this.districtcode;
	    }

	    
	    public void setDistrictcode(String districtcode) {
	        this.districtcode = districtcode;
	    }


	@Column(name = "centercode", length = 5)
	    public String getCentercode() {
	        return this.centercode;
	    }

	    
	    public void setCentercode(String centercode) {
	        this.centercode = centercode;
	    }

	
	@Temporal(TemporalType.DATE)
	@Column(name = "admissiondate", length = 10)
	public Date getAdmissiondate() {
		return this.admissiondate;
	}

	public void setAdmissiondate(Date admissiondate) {
		this.admissiondate = admissiondate;
	}

	@Column(name = "admissionnumber", length = 20)
	public String getAdmissionnumber() {
		return this.admissionnumber;
	}

	public void setAdmissionnumber(String admissionnumber) {
		this.admissionnumber = admissionnumber;
	}

	
	@Column(name = "Remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "createddate", length = 10)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "archive")
	public Integer getArchive() {
		return this.archive;
	}

	public void setArchive(Integer archive) {
		this.archive = archive;
	}

	@Column(name = "studentpic")
	public String getStudentpic() {
		return this.studentpic;
	}

	public void setStudentpic(String studentpic) {
		this.studentpic = studentpic;
	}

	@Column(name = "studentexternalid", unique = true, nullable = false, length = 45)
	public String getStudentexternalid() {
		return this.studentexternalid;
	}

	public void setStudentexternalid(String studentexternalid) {
		this.studentexternalid = studentexternalid;
	}

	@Column(name = "guardiandetails", length = 200)
	public String getGuardiandetails() {
		return this.guardiandetails;
	}

	public void setGuardiandetails(String guardiandetails) {
		this.guardiandetails = guardiandetails;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}

	@Column(name = "religion")
    public String getReligion() {
        return this.religion;
    }

    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    public String getEducation() {
        return this.education;
    }

    
    public void setEducation(String education) {
        this.education = education;
    }

    
    public String getAdmittedin() {
        return this.admittedin;
    }

    
    public void setAdmittedin(String admittedin) {
        this.admittedin = admittedin;
    }

    
    public Integer getPassedout() {
        return this.passedout;
    }

    
    public void setPassedout(Integer passedout) {
        this.passedout = passedout;
    }

    
    public Integer getDroppedout() {
        return this.droppedout;
    }

    
    public void setDroppedout(Integer droppedout) {
        this.droppedout = droppedout;
    }

	@Override
	public int compareTo(Student student) {
		Integer sid = student.getSid();
        return Integer.compare(this.sid, sid);
	}
  
}
