package com.model.student.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 14 Feb, 2018 12:05:32 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.model.degreedetails.dto.Degreedetails;
import com.model.pudetails.dto.Pudetails;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", uniqueConstraints = @UniqueConstraint(columnNames = "studentexternalid"))
public class Student implements java.io.Serializable {

	private Integer sid;
	private String name;
	private String classstudying;
	private String classadmittedin;
	private Integer age;
	private String gender;
	private Date dateofbirth;
	private String bloodgroup;
	private String nationality;
	private String religion;
	private Date admissiondate;
	private String admissionnumber;
	private String mothertongue;
	private String remarks;
	private Date createddate;
	private Integer archive;
	private String studentpic;
	private String studentexternalid;
	private Date crecorddate;
	private String placeofbirth;
	private Integer nooftc;
	private Date dateoftc;
	private String classonleaving;
	private Date dateleaving;
	private String reasonleaving;
	private Integer notcissued;
	private Date datetcissued;
	private String guardiandetails;
	private int branchid;
	private Pudetails pudetails;
	private Degreedetails degreedetails;
	private Integer passedout;
	private Integer droppedout;
	private Integer leftout;
	
	private String studentscastecertno;
	private String caste;
	private Integer sts;
	private Integer rte;
	private String bankbranch;
	private String accno;
	private String bankifsc;
	
	private String studentdoc1;
	private String studentdoc2;
	private String studentdoc3;
	private String studentdoc4;
	private String studentdoc5;
	private String studentdoc6;
	private String studentdoc7;
	private String studentdoc8;
	private String studentdoc9;
	private String studentdoc10;
	
	private String tenthboard;
	private String tenthyearofpassing;
	private String tenthnoofattempts;
	private String tenthtotalmarkssecured;
	private String tenthpercentage;
	private String twelthboard;
	private String twelthyearofpassing;
	private String twelthnoofattempts;
	private String twelthtotalmarkssecured;
	private String twelthpercentage;
	private String markscard10;
	private String markscard12;
	private String certificatemigration;
	private String eligibilitycertificate;
	private String transfercertificate;
	private String conductcertificate;
	private String adharcard;
	private String passportsizephotos;
	private String schoollastattended;
	
	public Student() {
	}

	public Student(String name, String studentexternalid) {
		this.name = name;
		this.studentexternalid = studentexternalid;
	}

	public Student(String name, String classstudying, String classadmittedin,
			Integer age, String gender, Date dateofbirth, String bloodgroup,
			String nationality, String religion, 
			Date admissiondate, String admissionnumber, String mothertongue,
			String remarks, String schoollastattended, 
			Date createddate, Integer archive, String studentpic,
			String studentexternalid, Date crecorddate,
			String placeofbirth, Integer nooftc, Date dateoftc,
			String classonleaving, Date dateleaving, String reasonleaving,
			Integer notcissued, Date datetcissued, String guardiandetails, int branchid,
			Integer passedout, Integer droppedout, Integer leftout,String studentscastecertno,String caste,
			Integer sts, Integer rte, String bankbranch, String accno, String bankifsc,
			String studentdoc1, String studentdoc2, String studentdoc3, String studentdoc4, String studentdoc5,
			String studentdoc6, String studentdoc7, String studentdoc8, String studentdoc9, String studentdoc10,
			String tenthboard,String tenthyearofpassing,String tenthnoofattempts,String tenthtotalmarkssecured,String tenthpercentage,String twelthboard,String twelthyearofpassing,String twelthnoofattempts,String twelthtotalmarkssecured,String twelthpercentage,String markscard10,String markscard12,String certificatemigration,String eligibilitycertificate,String transfercertificate,String conductcertificate,String adharcard,String passportsizephotos) {
		this.name = name;
		this.classstudying = classstudying;
		this.classadmittedin = classadmittedin;
		this.age = age;
		this.gender = gender;
		this.dateofbirth = dateofbirth;
		this.bloodgroup = bloodgroup;
		this.nationality = nationality;
		this.religion = religion;
		this.admissiondate = admissiondate;
		this.admissionnumber = admissionnumber;
		this.mothertongue = mothertongue;
		this.remarks = remarks;
		this.createddate = createddate;
		this.archive = archive;
		this.studentpic = studentpic;
		this.studentexternalid = studentexternalid;
		this.crecorddate = crecorddate;
		this.placeofbirth = placeofbirth;
		this.nooftc = nooftc;
		this.dateoftc = dateoftc;
		this.classonleaving = classonleaving;
		this.dateleaving = dateleaving;
		this.reasonleaving = reasonleaving;
		this.notcissued = notcissued;
		this.datetcissued = datetcissued;
		this.guardiandetails = guardiandetails;
		this.branchid = branchid;
		this.passedout = passedout;
		this.droppedout = droppedout;
		this.leftout = leftout;
		this.studentscastecertno = studentscastecertno;
		this.caste = caste;
		this.sts=sts;
		this.rte=rte;
		this.bankbranch=bankbranch;
		this.accno=accno;
		this.bankifsc=bankifsc;
		this.studentdoc1=studentdoc1;
		this.studentdoc2=studentdoc2;
		this.studentdoc3=studentdoc3;
		this.studentdoc4=studentdoc4;
		this.studentdoc5=studentdoc5;
		this.studentdoc6=studentdoc6;
		this.studentdoc7=studentdoc7;
		this.studentdoc8=studentdoc8;
		this.studentdoc9=studentdoc9;
		this.studentdoc10=studentdoc10;
		this.tenthboard=tenthboard;
		this.tenthyearofpassing=tenthyearofpassing;
		this.tenthnoofattempts=tenthnoofattempts;
		this.tenthtotalmarkssecured=tenthtotalmarkssecured;
		this.tenthpercentage=tenthpercentage;
		this.twelthboard=twelthboard;
		this.twelthyearofpassing=twelthyearofpassing;
		this.twelthnoofattempts=twelthnoofattempts;
		this.twelthtotalmarkssecured=twelthtotalmarkssecured;
		this.twelthpercentage=twelthpercentage;
		this.markscard10=markscard10;
		this.markscard12=markscard12;
		this.certificatemigration=certificatemigration;
		this.eligibilitycertificate=eligibilitycertificate;
		this.transfercertificate=transfercertificate;
		this.conductcertificate=conductcertificate;
		this.adharcard=adharcard;
		this.passportsizephotos=passportsizephotos;
		this.schoollastattended=schoollastattended;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "classstudying", length = 45)
	public String getClassstudying() {
		return this.classstudying;
	}

	public void setClassstudying(String classstudying) {
		this.classstudying = classstudying;
	}

	@Column(name = "classadmittedin", length = 45)
	public String getClassadmittedin() {
		return this.classadmittedin;
	}

	public void setClassadmittedin(String classadmittedin) {
		this.classadmittedin = classadmittedin;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 10)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "bloodgroup", length = 45)
	public String getBloodgroup() {
		return this.bloodgroup;
	}

	public void setBloodgroup(String bloodgroup) {
		this.bloodgroup = bloodgroup;
	}

	@Column(name = "nationality", length = 45)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "religion", length = 45)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "admissiondate", length = 10)
	public Date getAdmissiondate() {
		return this.admissiondate;
	}

	public void setAdmissiondate(Date admissiondate) {
		this.admissiondate = admissiondate;
	}

	@Column(name = "admissionnumber", length = 20)
	public String getAdmissionnumber() {
		return this.admissionnumber;
	}

	public void setAdmissionnumber(String admissionnumber) {
		this.admissionnumber = admissionnumber;
	}

	@Column(name = "mothertongue", length = 45)
	public String getMothertongue() {
		return this.mothertongue;
	}

	public void setMothertongue(String mothertongue) {
		this.mothertongue = mothertongue;
	}

	@Column(name = "Remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "createddate", length = 10)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "archive")
	public Integer getArchive() {
		return this.archive;
	}

	public void setArchive(Integer archive) {
		this.archive = archive;
	}

	@Column(name = "studentpic")
	public String getStudentpic() {
		return this.studentpic;
	}

	public void setStudentpic(String studentpic) {
		this.studentpic = studentpic;
	}

	@Column(name = "studentexternalid", unique = true, nullable = false, length = 45)
	public String getStudentexternalid() {
		return this.studentexternalid;
	}

	public void setStudentexternalid(String studentexternalid) {
		this.studentexternalid = studentexternalid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "crecorddate", length = 10)
	public Date getCrecorddate() {
		return this.crecorddate;
	}

	public void setCrecorddate(Date crecorddate) {
		this.crecorddate = crecorddate;
	}

	@Column(name = "placeofbirth", length = 100)
	public String getPlaceofbirth() {
		return this.placeofbirth;
	}

	public void setPlaceofbirth(String placeofbirth) {
		this.placeofbirth = placeofbirth;
	}

	@Column(name = "nooftc")
	public Integer getNooftc() {
		return this.nooftc;
	}

	public void setNooftc(Integer nooftc) {
		this.nooftc = nooftc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateoftc", length = 10)
	public Date getDateoftc() {
		return this.dateoftc;
	}

	public void setDateoftc(Date dateoftc) {
		this.dateoftc = dateoftc;
	}

	@Column(name = "classonleaving", length = 45)
	public String getClassonleaving() {
		return this.classonleaving;
	}

	public void setClassonleaving(String classonleaving) {
		this.classonleaving = classonleaving;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateleaving", length = 10)
	public Date getDateleaving() {
		return this.dateleaving;
	}

	public void setDateleaving(Date dateleaving) {
		this.dateleaving = dateleaving;
	}

	@Column(name = "reasonleaving", length = 500)
	public String getReasonleaving() {
		return this.reasonleaving;
	}

	public void setReasonleaving(String reasonleaving) {
		this.reasonleaving = reasonleaving;
	}

	@Column(name = "notcissued")
	public Integer getNotcissued() {
		return this.notcissued;
	}

	public void setNotcissued(Integer notcissued) {
		this.notcissued = notcissued;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datetcissued", length = 10)
	public Date getDatetcissued() {
		return this.datetcissued;
	}

	public void setDatetcissued(Date datetcissued) {
		this.datetcissued = datetcissued;
	}

	@Column(name = "guardiandetails", length = 200)
	public String getGuardiandetails() {
		return this.guardiandetails;
	}

	public void setGuardiandetails(String guardiandetails) {
		this.guardiandetails = guardiandetails;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}

    
    public Pudetails getPudetails() {
        return this.pudetails;
    }

    
    public void setPudetails(Pudetails pudetails) {
        this.pudetails = pudetails;
    }

    public Degreedetails getDegreedetails() {
        return this.degreedetails;
    }

    
    public void setDegreedetails(Degreedetails degreedetails) {
        this.degreedetails = degreedetails;
    }
    
    @Column(name = "passedout")
	public Integer getPassedout() {
		return passedout;
	}

	public void setPassedout(Integer passedout) {
		this.passedout = passedout;
	}

	@Column(name = "droppedout")
	public Integer getDroppedout() {
		return droppedout;
	}

	public void setDroppedout(Integer droppedout) {
		this.droppedout = droppedout;
	}

	@Column(name = "leftout")
	public Integer getLeftout() {
		return leftout;
	}

	public void setLeftout(Integer leftout) {
		this.leftout = leftout;
	}


	public String getStudentscastecertno() {
		return studentscastecertno;
	}

	public void setStudentscastecertno(String studentscastecertno) {
		this.studentscastecertno = studentscastecertno;
	}

	public Integer getSts() {
		return sts;
	}

	public void setSts(Integer sts) {
		this.sts = sts;
	}

	public Integer getRte() {
		return rte;
	}

	public void setRte(Integer rte) {
		this.rte = rte;
	}

	public String getBankbranch() {
		return bankbranch;
	}

	public void setBankbranch(String bankbranch) {
		this.bankbranch = bankbranch;
	}

	public String getAccno() {
		return accno;
	}

	public void setAccno(String accno) {
		this.accno = accno;
	}

	public String getBankifsc() {
		return bankifsc;
	}

	public void setBankifsc(String bankifsc) {
		this.bankifsc = bankifsc;
	}

	public String getStudentdoc1() {
		return studentdoc1;
	}

	public void setStudentdoc1(String studentdoc1) {
		this.studentdoc1 = studentdoc1;
	}

	public String getStudentdoc2() {
		return studentdoc2;
	}

	public void setStudentdoc2(String studentdoc2) {
		this.studentdoc2 = studentdoc2;
	}

	public String getStudentdoc3() {
		return studentdoc3;
	}

	public void setStudentdoc3(String studentdoc3) {
		this.studentdoc3 = studentdoc3;
	}

	public String getStudentdoc4() {
		return studentdoc4;
	}

	public void setStudentdoc4(String studentdoc4) {
		this.studentdoc4 = studentdoc4;
	}

	public String getStudentdoc5() {
		return studentdoc5;
	}

	public void setStudentdoc5(String studentdoc5) {
		this.studentdoc5 = studentdoc5;
	}

	public String getStudentdoc6() {
		return studentdoc6;
	}

	public void setStudentdoc6(String studentdoc6) {
		this.studentdoc6 = studentdoc6;
	}

	public String getStudentdoc7() {
		return studentdoc7;
	}

	public void setStudentdoc7(String studentdoc7) {
		this.studentdoc7 = studentdoc7;
	}

	public String getStudentdoc8() {
		return studentdoc8;
	}

	public void setStudentdoc8(String studentdoc8) {
		this.studentdoc8 = studentdoc8;
	}

	public String getStudentdoc9() {
		return studentdoc9;
	}

	public void setStudentdoc9(String studentdoc9) {
		this.studentdoc9 = studentdoc9;
	}

	public String getStudentdoc10() {
		return studentdoc10;
	}

	public void setStudentdoc10(String studentdoc10) {
		this.studentdoc10 = studentdoc10;
	}

	public String getTenthboard() {
		return tenthboard;
	}

	public void setTenthboard(String tenthboard) {
		this.tenthboard = tenthboard;
	}

	public String getTenthyearofpassing() {
		return tenthyearofpassing;
	}

	public void setTenthyearofpassing(String tenthyearofpassing) {
		this.tenthyearofpassing = tenthyearofpassing;
	}

	public String getTenthnoofattempts() {
		return tenthnoofattempts;
	}

	public void setTenthnoofattempts(String tenthnoofattempts) {
		this.tenthnoofattempts = tenthnoofattempts;
	}

	public String getTenthtotalmarkssecured() {
		return tenthtotalmarkssecured;
	}

	public void setTenthtotalmarkssecured(String tenthtotalmarkssecured) {
		this.tenthtotalmarkssecured = tenthtotalmarkssecured;
	}

	public String getTenthpercentage() {
		return tenthpercentage;
	}

	public void setTenthpercentage(String tenthpercentage) {
		this.tenthpercentage = tenthpercentage;
	}

	public String getTwelthboard() {
		return twelthboard;
	}

	public void setTwelthboard(String twelthboard) {
		this.twelthboard = twelthboard;
	}

	public String getTwelthyearofpassing() {
		return twelthyearofpassing;
	}

	public void setTwelthyearofpassing(String twelthyearofpassing) {
		this.twelthyearofpassing = twelthyearofpassing;
	}

	public String getTwelthnoofattempts() {
		return twelthnoofattempts;
	}

	public void setTwelthnoofattempts(String twelthnoofattempts) {
		this.twelthnoofattempts = twelthnoofattempts;
	}

	public String getTwelthtotalmarkssecured() {
		return twelthtotalmarkssecured;
	}

	public void setTwelthtotalmarkssecured(String twelthtotalmarkssecured) {
		this.twelthtotalmarkssecured = twelthtotalmarkssecured;
	}

	public String getTwelthpercentage() {
		return twelthpercentage;
	}

	public void setTwelthpercentage(String twelthpercentage) {
		this.twelthpercentage = twelthpercentage;
	}

	public String getMarkscard10() {
		return markscard10;
	}

	public void setMarkscard10(String markscard10) {
		this.markscard10 = markscard10;
	}

	public String getMarkscard12() {
		return markscard12;
	}

	public void setMarkscard12(String markscard12) {
		this.markscard12 = markscard12;
	}

	public String getCertificatemigration() {
		return certificatemigration;
	}

	public void setCertificatemigration(String certificatemigration) {
		this.certificatemigration = certificatemigration;
	}

	public String getEligibilitycertificate() {
		return eligibilitycertificate;
	}

	public void setEligibilitycertificate(String eligibilitycertificate) {
		this.eligibilitycertificate = eligibilitycertificate;
	}

	public String getTransfercertificate() {
		return transfercertificate;
	}

	public void setTransfercertificate(String transfercertificate) {
		this.transfercertificate = transfercertificate;
	}

	public String getConductcertificate() {
		return conductcertificate;
	}

	public void setConductcertificate(String conductcertificate) {
		this.conductcertificate = conductcertificate;
	}

	public String getAdharcard() {
		return adharcard;
	}

	public void setAdharcard(String adharcard) {
		this.adharcard = adharcard;
	}

	public String getPassportsizephotos() {
		return passportsizephotos;
	}

	public void setPassportsizephotos(String passportsizephotos) {
		this.passportsizephotos = passportsizephotos;
	}

	public String getSchoollastattended() {
		return schoollastattended;
	}

	public void setSchoollastattended(String schoollastattended) {
		this.schoollastattended = schoollastattended;
	}

	public String getCaste() {
		return caste;
	}

	public void setCaste(String caste) {
		this.caste = caste;
	}
	
	
	
}
