package com.model.student.dto;

// default package
// Generated 24 Jul, 2015 12:41:34 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Studentfeesstructure generated by hbm2java
 */
@Entity
@Table(name = "studentfeesstructure", catalog = "school")
public class Studentfeesstructure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer sfsid;
	private Integer sid;
	private String feescategory;
	private String feesamount;
	private String academicyear;

	public Studentfeesstructure() {
	}

	public Studentfeesstructure(Integer sid, String feescategory,
			String feesamount, String academicyear) {
		this.sid = sid;
		this.feescategory = feescategory;
		this.feesamount = feesamount;
		this.academicyear = academicyear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sfsid", unique = true, nullable = false)
	public Integer getSfsid() {
		return this.sfsid;
	}

	public void setSfsid(Integer sfsid) {
		this.sfsid = sfsid;
	}

	@Column(name = "sid")
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "feescategory", length = 100)
	public String getFeescategory() {
		return this.feescategory;
	}

	public void setFeescategory(String feescategory) {
		this.feescategory = feescategory;
	}

	@Column(name = "feesamount", length = 45)
	public String getFeesamount() {
		return this.feesamount;
	}

	public void setFeesamount(String feesamount) {
		this.feesamount = feesamount;
	}

	@Column(name = "academicyear", length = 45)
	public String getAcademicyear() {
		return this.academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}

}
