package org.ideoholic.curium.model.examdetails.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 19 Aug, 2016 8:15:22 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Exams generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "exams")
public class Exams implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exid", unique = true, nullable = false)
	private Integer exid;

	@Column(name = "examname", length = 45)
	private String examname;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "branchid")
	private int userid;

	@Column(name="success")
	private boolean success;

}
