package org.ideoholic.curium.model.examdetails.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 31 Mar, 2018 10:55:17 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Examschedule generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "examschedule")
public class Examschedule implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idexamschedule", unique = true, nullable = false)
	private Integer idexamschedule;

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	private Date date;

	@Column(name = "starttime", length = 20)
	private String starttime;

	@Column(name = "endtime", length = 20)
	private String endtime;

	@Column(name = "subject", length = 30)
	private String subject;

	@Column(name = "examname", length = 30)
	private String examname;

	@Column(name = "classes", length = 45)
	private String classes;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
