version: '3.3'

services:
  curium_service:
    image: ideoholic/curium:develop  # Use the image from Docker Hub
    container_name: curium-application-service
    ports:
      - "8123:8080"  # Map internal port 8080 to external port 8123
    networks:
      - curium_default
    environment:
      SPRING_APPLICATION_NAME: curium_service
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.mariadb.jdbc.Driver
      SPRING_DATASOURCE_PASSWORD: root
      # Use the MariaDB container's network alias / container name on the shared Docker network.
      SPRING_DATASOURCE_JDBC_URL: jdbc:mariadb://curium_mysql:3306/
      SPRING_DATASOURCE_USERNAME: root
	  SPRING_CONTEXT_PATH: /school

networks:
  curium_default:
    external: true


# Start the application using: docker-compose up --build -d
# Stop the application using: docker-compose down
# To remove any dangling images created during build: docker rmi $(docker images -f "dangling=true" -q)
