package com.model.user.dto;

// default package
// Generated 12 Sep, 2014 6:03:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "school")
public class Login implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer lid;
	private String username1;
	private String password1;
	private String usertype1;

	public Login() {
	}

	public Login(String username1, String password1, String usertype1) {
		this.username1 = username1;
		this.password1 = password1;
		this.usertype1 = usertype1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "lid", unique = true, nullable = false)
	public Integer getLid() {
		return this.lid;
	}

	public void setLid(Integer lid) {
		this.lid = lid;
	}

	@Column(name = "username1", nullable = false, length = 45)
	public String getUsername() {
		return this.username1;
	}

	public void setUsername(String username1) {
		this.username1 = username1;
	}

	@Column(name = "password1", nullable = false, length = 45)
	public String getPassword1() {
		return this.password1;
	}

	public void setPassword1(String password1) {
		this.password1 = password1;
	}
	@Column(name = "usertype1", length = 45)
	public String getUsertype1() {
		return this.usertype1;
	}

	public void setUsertype1(String usertype1) {
		this.usertype1 = usertype1;
	}

}
