package com.model.mess.card.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * messItems generated by hbm2java
 */
@Entity
@Table(name = "mess_card")
public class Card implements java.io.Serializable {

	private Integer id;
	private Integer sid;
	private Date validfrom;
	private Date validto;
	
	public Card() {
	}

	public Card(Integer sid, Date validfrom, Date validto) {
		this.sid = sid;
		this.validfrom = validfrom;
		this.validto = validto;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Date getValidfrom() {
		return validfrom;
	}

	public void setValidfrom(Date validfrom) {
		this.validfrom = validfrom;
	}

	public Date getValidto() {
		return validto;
	}

	public void setValidto(Date validto) {
		this.validto = validto;
	}
}
