package org.ideoholic.curium.model.position.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 16 Jan, 2015 12:53:58 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Position generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "position")
public class Position implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "positionid", unique = true, nullable = false)
	private Integer positionid;

	@Column(name = "positionname", length = 100)
	private String positionname;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
