package org.ideoholic.curium.model.mess.stockentry.dto;

import static javax.persistence.GenerationType.AUTO;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_stockentry")
public class MessStockEntry implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "externalid")
	private String externalid;

	@Column(name = "batchno")
	private String batchno;

	@Column(name = "quantity")
	private Float quantity;

	@Column(name = "itemunitprice")
	private Float itemunitprice;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "itemid")
	private Integer itemid;

	@Column(name = "availablequantity")
	private Float availablequantity;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "invoicedetailsid", unique = true, nullable = false)
	private MessInvoiceDetails messinvoicedetails;

	@Column(name = "status")
	private String status;

	@Column(name = "userid")
	private int userid;

	@Column(name = "receiveddate")
	private Date receiveddate;

	private Integer invoicedetailsid;
	private Float sgst;
	private Float cgst;


}