package org.ideoholic.curium.model.mess.stockentry.dto;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_invoicedetails")
public class MessInvoiceDetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "externalid")
	private String externalid;

	@Column(name = "suppliersid")
	private Integer suppliersid;

	@Column(name = "supplierreferenceno")
	private String supplierreferenceno;

	@Column(name = "invoicetotal")
	private Float invoicetotal;

	@Column(name = "entrydate", length = 10)
	private Date entrydate;

	@Column(name = "invoicedate", length = 10)
	private Date invoicedate;

	@Column(name = "status")
	private String status;

	@Column(name = "voucherid")
	private Integer voucherid;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	@OneToMany(mappedBy = "messinvoicedetails")
	private List<MessStockEntry> messStockEntryList;

}
