package com.model.mess.stockentry.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.model.mess.item.dto.MessItems;
import com.model.mess.supplier.dto.MessSuppliers;

/**
 * messItems generated by hbm2java
 */
@Entity
@Table(name = "mess_stockentry")
public class MessStockEntry implements java.io.Serializable {

	private Integer id;
	private String externalid;
	private String batchno;
	private Float quantity;
	private Float itemunitprice;
	private Integer branchid;
	private Integer itemid;
	private Float availablequantity;
	private MessInvoiceDetails messinvoicedetails;
	private String status;
	private int userid;
	private Date receiveddate;
	
	public MessStockEntry() {
	}
	
	public MessStockEntry(Integer id, String externalid, String batchno, Float quantity, Float itemunitprice,Integer branchid, Integer itemsid, Float availablequantity, String status, int userid, Date receiveddate) {
		this.id = id;
		this.externalid = externalid;
		this.batchno = batchno;
		this.quantity = quantity;
		this.itemunitprice = itemunitprice;
		this.branchid = branchid;
		this.itemid = itemsid;
		this.availablequantity = availablequantity;
		this.status = status;
		this.userid = userid;
		this.receiveddate = receiveddate;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getExternalid() {
		return externalid;
	}

	public void setExternalid(String externalid) {
		this.externalid = externalid;
	}

	public String getBatchno() {
		return batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	public Float getQuantity() {
		return quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public Float getItemunitprice() {
		return itemunitprice;
	}

	public void setItemunitprice(Float itemunitprice) {
		this.itemunitprice = itemunitprice;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}

	public MessInvoiceDetails getMessinvoicedetails() {
		return messinvoicedetails;
	}

	public void setMessinvoicedetails(MessInvoiceDetails messinvoicedetails) {
		this.messinvoicedetails = messinvoicedetails;
	}

	public Integer getItemid() {
		return itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	public Float getAvailablequantity() {
		return availablequantity;
	}

	public void setAvailablequantity(Float availablequantity) {
		this.availablequantity = availablequantity;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Date getReceiveddate() {
		return receiveddate;
	}

	public void setReceiveddate(Date receiveddate) {
		this.receiveddate = receiveddate;
	}


}
