package org.ideoholic.curium.model.mess.stockentry.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.mess.item.dto.MessItems;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_stockavailable")
public class MessStockAvailability implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "availablestock")
	private Float availablestock;

	@Column(name = "minstock")
	private Integer minstock;

	@Column(name = "branchid")
	private Integer branchid;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "itemid", unique = true, nullable = false)
	private MessItems messitems;

	@Column(name = "userid")
	private int userid;

}
