package com.model.order.booksinfo.dto;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * messItems generated by hbm2java
 */
@Entity
@Table(name = "booksinfo")
public class BooksInfo implements java.io.Serializable {

	private Integer id;
	private String title;
	private String author;
	
	public BooksInfo() {
	}

	public BooksInfo(String title, String author) {
		this.title = title;
		this.author = author;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	
}
