package org.ideoholic.curium.model.subjectdetails.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 15 Aug, 2016 12:22:36 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Subject generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "subjectmaster")
public class Subjectmaster implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "subjectid", unique = true, nullable = false)
	private Integer subjectid;

	@Column(name = "subjectname", length = 100)
	private String subjectname;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
