package org.ideoholic.curium.model.subjectdetails.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 15 Aug, 2016 12:22:36 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Subject generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "subsubjectmaster")
public class SubSubject implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "subsubjectname", length = 45)
	private String subsubjectname;

	@Column(name = "subjectid")
	private Integer subjectid;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
