smsuser=littleflower
smssender=LFHSCL
apikey=KK6x7XMHGEe3vxs6eOgNEg
peid=1701168683301885640

feessendsms=no
feestemplateid=1007542155026968676
feestemplatemessage=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From Little Flower,CURIUM Software, www.ideoholic.com

absentsendsms=yes
absenttemplateid=1707172560417179972
absenttemplatemessage= Dear parents, your son/daughter var1 studying in var2 is absent today. -LFHSCL

holidaysendsms=yes
holidaytemplateid=1707169268751202894
holidaytemplatemessage=Dear Parents, A warm regard from school. This is to inform you that there will be holiday on var1 on the account of var2 - LFHSCL

examssendsms=yes
examstemplateid=1707169268274028551
examstemplatemessage=Dear Parents, A warm regard from School, this is to inform you that var1 for the academic Year var2 is going to be held on var3 - LFHSCL

booksalesendsms=yes
booksaletemplateid=1707174971445680737
booksaletemplatemessage=Dear Parents, We would like to inform you that the book sale process is currently in progress for classes var1 Parents are kindly requested to visit the school and complete the purchase of books at the earliest convenience. Thank you for your cooperation and support. School Management -LFHSCL

ptmsendsms=yes
ptmtemplateid=1707169269085761617
ptmtemplatemessage=Dear parents, A warm regard from school. this is to inform you that Parent-Teacher Meet from classes var1 will be held on var2 at var3. LFHSCL

scholarshipsendsms=yes
scholarshiptemplateid=1707170106833660942
scholarshiptemplatemessage=Dear parents, Govt. of Karnataka has announced scholarship for var1. you can register at high school on or before var2. - LFHSCL

feesremindersendsms=yes
feesremindertemplateid=1707169268790622004
feesremindertemplatemessage=Dear Parents A warm regard from school this is to inform you that please clear yours ward term fee on or before var1 - LFHSCL

sendcancelappointmentsms=no
sendappointmentsms=no
sendjobsms=no
sendcompletedquerysms=no
sendcasessms=no
sendcaveatssms=no

feesstartmonth=01/04/2024
feesmonths2=April,May,June,July,August,September,October,November,December,January,February,March

#Little Flower
#Branch 1 start

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid2=49
itemaccountidexpense2=50
transportationexpenses2=37
PAS2=51
CAS2=52

admin2=1
studentfeesreceivable2=6
bank2=2
studentfeesincome2=29
unearnedstudentfeesincome2=48

#Cost of goods sold
itemaccountidexpense2=50
#End
cashinhandaccountid2=1
#Income Account
incomeaccount2=54
#Billing
admin2=1
bank2=2
wajid2=55
shahbaz2=56

cashledgers2=1
bankledgers2=2
excludeincomeledger2=6:48
otherincome2=30
#Branch 1 End

#Branch 2 start

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid3=105
itemaccountidexpense3=106
transportationexpenses3=93
PAS3=107
CAS3=108

admin3=57
studentfeesreceivable3=62
sbibank3=58
studentfeesincome3=85
unearnedstudentfeesincome3=104

#Cost of goods sold
itemaccountidexpense3=106
#End
cashinhandaccountid3=57
#Income Account
incomeaccount3=108
shahbaz3=112


deeniyatexamids2=9,10
TermOneExams2=1,2,3,4
TermTwoExams2=5,6,7,8
OtherExamsSubjects2=6,7,14,15
preprimaryexamids2=11,12,13,14
TermOneExamsPreprimary2=11,12
TermTwoExamsPreprimary2=13,14

#TermOneExams2=1,2,3,4
#TermTwoExams2=5,6,7,8
#preprimaryexamids2=11,12,13,14
#TermOneExamsPreprimary2=11,12
#TermTwoExamsPreprimary2=13,14
#OtherExamsSubjects2=7,8
#Branch 2 End

#Branch 3 start

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid4=157
itemaccountidexpense4=158
transportationexpenses4=145
PAS4=51
CAS4=52

admin4=109
studentfeesreceivable4=114
sbibank4=110
studentfeesincome4=137
unearnedstudentfeesincome4=156

#Cost of goods sold
itemaccountidexpense4=50
#End
cashinhandaccountid4=1
#Income Account
incomeaccount4=162
#Branch 3 End
startdate=01/01/2023

