smsuser=brainystars
smssender=IDOHLC
apikey=
peid=1001978896612375681

feessendsms2=yes
feestemplateid=1007542155026968676
feestemplatemessage2=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From Brainy Stars,CURIUM Software, www.ideoholic.com

absentsendsms2=yes
absenttemplateid=1007195246827003685
absenttemplatemessage2= Dear Parents , Your ward var1 is absent on var2.From Brainy Stars School,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms2=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage2=Dear Parents, school will be closed on var1 due to var2. From, Brainy Stars, CURIUM Software - www.ideoholic.com

examssendsms2=yes
examstemplateid=1007107035630216525
examstemplatemessage2=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, Brainy Stars,CURIUM Software, www.ideoholic.com

feesremindersendsms2=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage2=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From Brainy Stars, www.ideoholic.com

sendcancelappointmentsms=no
sendappointmentsms=no
sendjobsms=no
sendcompletedquerysms=no
sendcasessms=no
sendcaveatssms=no

feesstartmonth=01/04/2025

#Scholar Group
#Branch 2 start

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
#current stock
itemaccountid2=49
#expense stock
itemaccountidexpense2=50
transportationexpenses2=37
PAS2=51
CAS2=52

adminacademy2=1
#Suspense A/c
studentfeesreceivable2=6
bank2=2
#Income from Student Fees 
studentfeesincome2=29
#Unearned Student Fees
unearnedstudentfeesincome2=48

#Cost of goods sold
itemaccountidexpense2=50
#End
cashinhandaccountid2=1
#Income Account
#Sales of Stock 
incomeaccount2=53
#Billing
adminacademy2=1
bank2=2

#Branch 2 End

#Branch 3 start

feessendsms3=yes
feestemplateid=1007542155026968676
feestemplatemessage3=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From Brainy Star,CURIUM Software, www.ideoholic.com

absentsendsms3=yes
absenttemplateid=1007195246827003685
absenttemplatemessage3= Dear Parents , Your ward var1 is absent on var2.From Brainy Star,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms3=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage3=Dear Parents, school will be closed on var1 due to var2. From, Brainy Star, CURIUM Software - www.ideoholic.com

examssendsms3=yes
examstemplateid=1007107035630216525
examstemplatemessage3=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, Brainy Star,CURIUM Software, www.ideoholic.com

feesremindersendsms3=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage3=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From Brainy Star, www.ideoholic.com

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid3=105
itemaccountidexpense3=106
transportationexpenses3=93
PAS3=107
CAS3=108

adminkidz3=55
studentfeesreceivable3=60
bank3=56
studentfeesincome3=84
unearnedstudentfeesincome3=104

#Cost of goods sold
itemaccountidexpense3=106
#End
cashinhandaccountid3=55
#Income Account
incomeaccount3=109


deeniyatexamids2=9,10
TermOneExams2=1,2,3,4
TermTwoExams2=5,6,7,8
OtherExamsSubjects2=6,7,14,15
preprimaryexamids2=11,12,13,14
TermOneExamsPreprimary2=11,12
TermTwoExamsPreprimary2=13,14

#TermOneExams2=1,2,3,4
#TermTwoExams2=5,6,7,8
#preprimaryexamids2=11,12,13,14
#TermOneExamsPreprimary2=11,12
#TermTwoExamsPreprimary2=13,14
#OtherExamsSubjects2=7,8
#Branch 3 End

#Branch 4 start


feessendsms4=yes
feestemplateid=1007542155026968676
feestemplatemessage4=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From Brainy Star,CURIUM Software, www.ideoholic.com

absentsendsms4=yes
absenttemplateid=1007195246827003685
absenttemplatemessage4= Dear Parents , Your ward var1 is absent on var2.From Brainy Star,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms4=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage4=Dear Parents, school will be closed on var1 due to var2. From, Brainy Star, CURIUM Software - www.ideoholic.com

examssendsms4=yes
examstemplateid=1007107035630216525
examstemplatemessage4=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, Brainy Star,CURIUM Software, www.ideoholic.com

feesremindersendsms4=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage4=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From Brainy Star, www.ideoholic.com


#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid4=158
itemaccountidexpense4=159
transportationexpenses4=146
PAS4=160
CAS4=161

adminchamps4=110
studentfeesreceivable4=115
bank4=111
studentfeesincome4=138
unearnedstudentfeesincome4=157

#Cost of goods sold
itemaccountidexpense4=159
#End
cashinhandaccountid4=110
#Income Account
incomeaccount4=162
#Branch 4 End



#Branch 5 start

feessendsms5=yes
feestemplateid=1007542155026968676
feestemplatemessage5=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From Shining Star Academy,CURIUM Software, www.ideoholic.com

absentsendsms5=yes
absenttemplateid=1007195246827003685
absenttemplatemessage5= Dear Parents , Your ward var1 is absent on var2.From Shining Star Academy,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms5=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage5=Dear Parents, school will be closed on var1 due to var2. From, Shining Star Academy, CURIUM Software - www.ideoholic.com

examssendsms5=yes
examstemplateid=1007107035630216525
examstemplatemessage5=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, Shining Star Academy,CURIUM Software, www.ideoholic.com

feesremindersendsms5=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage5=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From Shining Star Academy, www.ideoholic.com

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid5=211
itemaccountidexpense5=212
transportationexpenses5=199
PAS5=213
CAS5=214

scholaracademy5=163
studentfeesreceivable5=168
bank5=164
studentfeesincome5=191
unearnedstudentfeesincome5=210

#Cost of goods sold
itemaccountidexpense5=212
#End
cashinhandaccountid5=163
#Income Account
incomeaccount5=215
#Billing
adminstar5=163
bank5=164

#Branch 5 End


#Branch 6 start

feessendsms6=yes
feestemplateid=1007542155026968676
feestemplatemessage6=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From T.M.S Campus,CURIUM Software, www.ideoholic.com

absentsendsms6=yes
absenttemplateid=1007195246827003685
absenttemplatemessage6= Dear Parents , Your ward var1 is absent on var2.From T.M.S Campus,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms6=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage6=Dear Parents, school will be closed on var1 due to var2. From, T.M.S Campus, CURIUM Software - www.ideoholic.com

examssendsms6=yes
examstemplateid=1007107035630216525
examstemplatemessage6=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, T.M.S Campus,CURIUM Software, www.ideoholic.com

feesremindersendsms6=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage6=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From T.M.S Campus, www.ideoholic.com

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid6=264
itemaccountidexpense6=265
transportationexpenses6=252
PAS6=266
CAS6=267

tms@scholar6=216
studentfeesreceivable6=221
bank6=217
studentfeesincome6=244
unearnedstudentfeesincome6=263

#Cost of goods sold
itemaccountidexpense6=265
#End
cashinhandaccountid6=216
#Income Account
incomeaccount6=268
#Billing
tms@scholar6=216
bank6=217

#Branch 6 End



#Branch 7 start


feessendsms7=yes
feestemplateid=1007542155026968676
feestemplatemessage7=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From SCANIK,CURIUM Software, www.ideoholic.com

absentsendsms7=yes
absenttemplateid=1007195246827003685
absenttemplatemessage7= Dear Parents , Your ward var1 is absent on var2.From SCANIK,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms7=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage7=Dear Parents, school will be closed on var1 due to var2. From, SCANIK, CURIUM Software - www.ideoholic.com

examssendsms7=yes
examstemplateid=1007107035630216525
examstemplatemessage7=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, SCANIK,CURIUM Software, www.ideoholic.com

feesremindersendsms7=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage7=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From SCANIK, www.ideoholic.com

#For Creating Suppliers Ledger
groupName=2
subGroupCode=3
ssGroupCode=12
accountcode=LCL0
#
itemaccountid7=317
itemaccountidexpense7=318
transportationexpenses7=305
PAS7=319
CAS7=320

admin@scanik7=269
studentfeesreceivable7=274
bank7=270
studentfeesincome7=297
unearnedstudentfeesincome7=316

#Cost of goods sold
itemaccountidexpense7=318
#End
cashinhandaccountid7=269
#Income Account
incomeaccount7=321
#Billing
admin@scanik7=269
bank7=270

#Branch 7 End


#Branch 8 start
feessendsms8=yes
feestemplateid=1007542155026968676
feestemplatemessage8=Dear Parents, your ward's fee of var1 has been received, Thank you for your payment.From Balwa School,CURIUM Software, www.ideoholic.com

absentsendsms8=yes
absenttemplateid=1007195246827003685
absenttemplatemessage8= Dear Parents , Your ward var1 is absent on var2.From Balwa School,CURIUM Software,IDEOHOLIC(www.ideoholic.com)

holidaysendsms8=yes
holidaytemplateid=1007193707203275126
holidaytemplatemessage8=Dear Parents, school will be closed on var1 due to var2. From, Balwa School, CURIUM Software - www.ideoholic.com

examssendsms8=yes
examstemplateid=1007107035630216525
examstemplatemessage8=Dear Parents, We would like to inform you that the var1 will commence from var2.Best regards, Balwa Schl,CURIUM Software, www.ideoholic.com

feesremindersendsms8=yes
feesremindertemplateid=1007426171089874345
feesremindertemplatemessage8=Dear parents,kindly note there is a pending fee payment.kindly make the payment before var1.Please ignore if already paid.From Balwa School, www.ideoholic.com

#current stock
itemaccountid8=370
#expense stock
itemaccountidexpense8=371
transportationexpenses8=358
PAS8=372
CAS8=373

admin@drzakir8=322
#Suspense A/c
studentfeesreceivable8=327
bank8=323
#Income from Student Fees 
studentfeesincome8=350
#Unearned Student Fees
unearnedstudentfeesincome8=369

#Cost of goods sold
itemaccountidexpense8=371
#End
cashinhandaccountid8=322
#Income Account
#Sales of Stock 
incomeaccount8=374
#Billing
admin@drzakir8=322
bank8=323

#Branch 8 End
