package com.model.hr.dto;

// default package
// Generated 18 Apr, 2018 3:59:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Leavetypemaster generated by hbm2java
 */
@Entity
@Table(name = "hr_leavetypemaster")
public class Leavetypemaster implements java.io.Serializable {

	private Integer idleavetypemaster;
	private String leavetypename;
	private int branchid;
	private int userid;
	
	public Leavetypemaster() {
	}

	public Leavetypemaster(String leavetypename, int branchid, int userid) {
		this.leavetypename = leavetypename;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idleavetypemaster", unique = true, nullable = false)
	public Integer getIdleavetypemaster() {
		return this.idleavetypemaster;
	}

	public void setIdleavetypemaster(Integer idleavetypemaster) {
		this.idleavetypemaster = idleavetypemaster;
	}

	@Column(name = "leavetypename", length = 100)
	public String getLeavetypename() {
		return this.leavetypename;
	}

	public void setLeavetypename(String leavetypename) {
		this.leavetypename = leavetypename;
	}
	
	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
