package com.model.hr.dto;

// default package
// Generated 24 Apr, 2018 11:34:11 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.model.employee.dto.Teacher;

/**
 * Payadvancesalary generated by hbm2java
 */
@Entity
@Table(name = "hr_payadvancesalary")
public class Payadvancesalary implements java.io.Serializable {

	private Integer idpayadvancesalary;
	private Integer idteacher;
	private String year;
	private String month;
	private Integer salaryfordays;
	private BigDecimal deductionpermonth;
	private BigDecimal amount;
	private String deductionstartmonth;
	private String deductionstartyear;
	private String status;
	private Teacher teacher;
	private String reason;
	private Date date;
	private int branchid;
	private int userid;
	
	public Payadvancesalary() {
	}

	public Payadvancesalary(Integer idteacher, String year, String month,
			Integer salaryfordays, BigDecimal deductionpermonth,
			BigDecimal amount, String deductionstartmonth,
			String deductionstartyear, Teacher teacher, String status, String reason, Date date,
			int branchid, int userid) {
		this.idteacher = idteacher;
		this.year = year;
		this.month = month;
		this.salaryfordays = salaryfordays;
		this.deductionpermonth = deductionpermonth;
		this.amount = amount;
		this.deductionstartmonth = deductionstartmonth;
		this.deductionstartyear = deductionstartyear;
		this.status = status;
		this.teacher = teacher;
		this.reason = reason;
		this.date = date;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpayadvancesalary", unique = true, nullable = false)
	public Integer getIdpayadvancesalary() {
		return this.idpayadvancesalary;
	}

	public void setIdpayadvancesalary(Integer idpayadvancesalary) {
		this.idpayadvancesalary = idpayadvancesalary;
	}

	@Column(name = "idteacher")
	public Integer getIdteacher() {
		return this.idteacher;
	}

	public void setIdteacher(Integer idteacher) {
		this.idteacher = idteacher;
	}

	@Column(name = "year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "month", length = 45)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "salaryfordays")
	public Integer getSalaryfordays() {
		return this.salaryfordays;
	}

	public void setSalaryfordays(Integer salaryfordays) {
		this.salaryfordays = salaryfordays;
	}

	@Column(name = "deductionpermonth", precision = 20, scale = 4)
	public BigDecimal getDeductionpermonth() {
		return this.deductionpermonth;
	}

	public void setDeductionpermonth(BigDecimal deductionpermonth) {
		this.deductionpermonth = deductionpermonth;
	}

	@Column(name = "amount", precision = 20, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "deductionstartmonth", length = 45)
	public String getDeductionstartmonth() {
		return this.deductionstartmonth;
	}

	public void setDeductionstartmonth(String deductionstartmonth) {
		this.deductionstartmonth = deductionstartmonth;
	}

	@Column(name = "deductionstartyear", length = 45)
	public String getDeductionstartyear() {
		return this.deductionstartyear;
	}

	public void setDeductionstartyear(String deductionstartyear) {
		this.deductionstartyear = deductionstartyear;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "status", length = 40)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reason", length = 500)
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "date", length = 10)
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
