package com.model.hr.dto;

// default package
// Generated 22 Apr, 2018 5:13:05 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.model.employee.dto.Teacher;

/**
 * Payheadstaffdetails generated by hbm2java
 */
@Entity
@Table(name = "hr_payheadstaffdetails")
public class Payheadstaffdetails implements java.io.Serializable {

	private Integer idpayheadstaffdetails;
	private int idteacher;
	private BigDecimal value;
	private String amountperc;
	private String academicyear;
	private Teacher teacher;
	private Payhead payhead;
	private int branchid;
	private int userid;
	
	public Payheadstaffdetails() {
	}

	public Payheadstaffdetails(int idteacher) {
		this.idteacher = idteacher;
	}

	public Payheadstaffdetails(int idteacher, BigDecimal value, String amountperc,
			String academicyear, Teacher teacher, Payhead payhead, int branchid, int userid) {
		this.idteacher = idteacher;
		this.value = value;
		this.amountperc = amountperc;
		this.academicyear = academicyear;
		this.teacher = teacher;
		this.payhead = payhead;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpayheadstaffdetails", unique = true, nullable = false)
	public Integer getIdpayheadstaffdetails() {
		return this.idpayheadstaffdetails;
	}

	public void setIdpayheadstaffdetails(Integer idpayheadstaffdetails) {
		this.idpayheadstaffdetails = idpayheadstaffdetails;
	}

	@Column(name = "idteacher", nullable = false)
	public int getIdteacher() {
		return this.idteacher;
	}

	public void setIdteacher(int idteacher) {
		this.idteacher = idteacher;
	}

	@Column(name = "value", precision = 20, scale = 4)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Column(name = "amountperc")
	public String getAmountperc() {
		return this.amountperc;
	}

	public void setAmountperc(String amountperc) {
		this.amountperc = amountperc;
	}

	@Column(name = "academicyear", length = 45)
	public String getAcademicyear() {
		return this.academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Payhead getPayhead() {
		return payhead;
	}

	public void setPayhead(Payhead payhead) {
		this.payhead = payhead;
	}
	
	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
