package com.model.hr.dto;

// default package
// Generated 30 Apr, 2018 6:08:33 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.model.employee.dto.Teacher;

/**
 * Processsalarydetails generated by hbm2java
 */
@Entity
@Table(name = "hr_processsalarydetails")
public class Processsalarydetails implements java.io.Serializable {

	private Integer idprocesssalarydetails;
	private Integer teacherid;
	private String month;
	private Integer year;
	private BigDecimal netpayment;
	private String status;
	private String academicyear;
	private Date processeddate;
	private Date issueddate;
	private Teacher teacher;
	private String paymenttype;
	private int branchid;
	private int userid;
	
	public Processsalarydetails() {
	}

	public Processsalarydetails(Integer teacherid, String month, Integer year,
			BigDecimal netpayment, String status, String academicyear,
			Date processeddate, Date issueddate, Teacher teacher, String paymenttype,
			int branchid, int userid) {
		this.teacherid = teacherid;
		this.month = month;
		this.year = year;
		this.netpayment = netpayment;
		this.status = status;
		this.academicyear = academicyear;
		this.processeddate = processeddate;
		this.issueddate = issueddate;
		this.teacher = teacher;
		this.paymenttype = paymenttype;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idprocesssalarydetails", unique = true, nullable = false)
	public Integer getIdprocesssalarydetails() {
		return this.idprocesssalarydetails;
	}

	public void setIdprocesssalarydetails(Integer idprocesssalarydetails) {
		this.idprocesssalarydetails = idprocesssalarydetails;
	}

	@Column(name = "teacherid")
	public Integer getTeacherid() {
		return this.teacherid;
	}

	public void setTeacherid(Integer teacherid) {
		this.teacherid = teacherid;
	}

	@Column(name = "month", length = 10)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "netpayment", precision = 20, scale = 0)
	public BigDecimal getNetpayment() {
		return this.netpayment;
	}

	public void setNetpayment(BigDecimal netpayment) {
		this.netpayment = netpayment;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "academicyear", length = 45)
	public String getAcademicyear() {
		return this.academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "processeddate", length = 10)
	public Date getProcesseddate() {
		return this.processeddate;
	}

	public void setProcesseddate(Date processeddate) {
		this.processeddate = processeddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "issueddate", length = 10)
	public Date getIssueddate() {
		return this.issueddate;
	}

	public void setIssueddate(Date issueddate) {
		this.issueddate = issueddate;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "paymenttype", length = 20)
	public String getPaymenttype() {
		return paymenttype;
	}

	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
