package com.model.position.dto;

// default package
// Generated 16 Jan, 2015 12:53:58 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "school")
public class Position implements java.io.Serializable {

	private Integer positionid;
	private String positionname;

	public Position() {
	}

	public Position(String positionname) {
		this.positionname = positionname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "positionid", unique = true, nullable = false)
	public Integer getPositionid() {
		return this.positionid;
	}

	public void setPositionid(Integer positionid) {
		this.positionid = positionid;
	}

	@Column(name = "positionname", length = 100)
	public String getPositionname() {
		return this.positionname;
	}

	public void setPositionname(String positionname) {
		this.positionname = positionname;
	}

}
