package org.ideoholic.curium.model.feescategory.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Feescategory generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Concession {
	private int sfsid;
	private int feescatid;
	private String concession;
	private String concessionOld;
}
