package org.ideoholic.curium.model.feescategory.dto;

import javax.persistence.Entity;

/**
 * Feescategory generated by hbm2java
 */

@Entity
public class Concession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int sfsid;
	private int feescatid;
	private String concession;
	private String concessionOld;

	public int getSfsid() {
		return sfsid;
	}

	public void setSfsid(int sfsid) {
		this.sfsid = sfsid;
	}

	public int getFeescatid() {
		return feescatid;
	}

	public void setFeescatid(int feescatid) {
		this.feescatid = feescatid;
	}

	public String getConcession() {
		return concession;
	}

	public void setConcession(String concession) {
		this.concession = concession;
	}

	public String getConcessionOld() {
		return concessionOld;
	}

	public void setConcessionOld(String concessionOld) {
		this.concessionOld = concessionOld;
	}

}
