package org.ideoholic.curium.model.feescategory.dto;

// default package
// Generated 6 Dec, 2014 11:27:37 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ideoholic.curium.model.subjectdetails.dto.Subjectmaster;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Feescategory generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "concession")
public class Concession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int sfsid;
	private int feescatid;
	private String concession;
	private String concessionOld;
	
	

	public int getSfsid() {
		return sfsid;
	}

	public void setSfsid(int sfsid) {
		this.sfsid = sfsid;
	}

	public int getFeescatid() {
		return feescatid;
	}

	public void setFeescatid(int feescatid) {
		this.feescatid = feescatid;
	}

	public String getConcession() {
		return concession;
	}

	public void setConcession(String concession) {
		this.concession = concession;
	}

	public String getConcessionOld() {
		return concessionOld;
	}

	public void setConcessionOld(String concessionOld) {
		this.concessionOld = concessionOld;
	}

}
