package org.ideoholic.curium.model.feescategory.dto;

import java.util.List;

import javax.persistence.CascadeType;

// default package
// Generated 6 Dec, 2014 11:27:37 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.ideoholic.curium.model.student.dto.Studentfeesstructure;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Feescategory generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "fee_feescategory")
public class Feescategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idfeescategory", unique = true, nullable = false)
	private Integer idfeescategory;

	@Column(name = "feescategoryname", length = 150)
	private String feescategoryname;

	@Column(name = "amount")
	private Integer amount;

	@Column(name = "particularname", length = 150)
	private String particularname;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	@Column(name = "academicyear", length = 20)
	private String academicyear;
	
	@Column(name = "totalinstallments")
	private int totalinstallments;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "feescategory")
	private List<Studentfeesstructure> feeStudentfeesstructureList;

}
