package com.model.attendance.dto;

// default package
// Generated 18 Jan, 2018 4:41:06 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Attendancemaster generated by hbm2java
 */
@Entity
@Table(name = "att_attendancemaster")
public class Attendancemaster implements java.io.Serializable {

	private Integer idattendancemaster;
	private String attendeeid;
	private String intime;
	private String outtime;
	private String weeklyoff;
	private String holidayname;
	private int branchid;
	private int userid;
	

	public Attendancemaster() {
	}

	public Attendancemaster(String attendeeid) {
		this.attendeeid = attendeeid;
	}

	public Attendancemaster(String attendeeid, String intime, String outtime,
			String weeklyoff, String holidayname, int branchid, int userid) {
		this.attendeeid = attendeeid;
		this.intime = intime;
		this.outtime = outtime;
		this.weeklyoff = weeklyoff;
		this.holidayname = holidayname;
		this.branchid = branchid;
		this.userid = userid; 
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idattendancemaster", unique = true, nullable = false)
	public Integer getIdattendancemaster() {
		return this.idattendancemaster;
	}

	public void setIdattendancemaster(Integer idattendancemaster) {
		this.idattendancemaster = idattendancemaster;
	}

	@Column(name = "attendeeid", nullable = false, length = 10)
	public String getAttendeeid() {
		return this.attendeeid;
	}

	public void setAttendeeid(String attendeeid) {
		this.attendeeid = attendeeid;
	}

	@Column(name = "intime", length = 10)
	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

	@Column(name = "outtime", length = 10)
	public String getOuttime() {
		return this.outtime;
	}

	public void setOuttime(String outtime) {
		this.outtime = outtime;
	}

	@Column(name = "weeklyoff", length = 50)
	public String getWeeklyoff() {
		return this.weeklyoff;
	}

	public void setWeeklyoff(String weeklyoff) {
		this.weeklyoff = weeklyoff;
	}

	@Column(name = "holidayname", length = 200)
	public String getHolidayname() {
		return this.holidayname;
	}

	public void setHolidayname(String holidayname) {
		this.holidayname = holidayname;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
