package org.ideoholic.curium.model.department.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 16 Jan, 2015 12:53:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Department generated by hbm2java
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "department")
public class Department implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "depid", unique = true, nullable = false)
	private Integer depid;

	@Column(name = "departmentname", length = 100)
	private String departmentname;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
