package org.ideoholic.curium.model.task.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.ideoholic.curium.model.employee.dto.Teacher;
import org.ideoholic.curium.model.job.dto.JobQuery;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "h_task")
public class Task implements java.io.Serializable {

	private Integer id;
	private Integer jobid;
	private Integer assignto;
	private String tasks;
	private String description;
	private String remarks;
	private Date expecteddeliverydate;
	private Date updateddate;
	private Integer branchid;
	private Integer updateduserid;
	private String status;
	private Teacher teacher;
	private JobQuery jobquery;
	
	public Task() {
	}

	public Task(Integer jobid,Integer assignto, String tasks,String description,String remarks, Date expecteddeliverydate, Integer branchid,
			Date updateddate, Integer updateduserid, String status){
		this.jobid = jobid;
		this.assignto = assignto;
		this.tasks = tasks;
		this.description = description;
		this.remarks = remarks;
		this.expecteddeliverydate = expecteddeliverydate;
		this.branchid = branchid;
		this.updateddate = updateddate;
		this.updateduserid = updateduserid;
		this.status = status;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Integer getUpdateduserid() {
		return updateduserid;
	}

	public void setUpdateduserid(Integer updateduserid) {
		this.updateduserid = updateduserid;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getAssignto() {
		return assignto;
	}

	public Date getUpdateddate() {
		return updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public void setAssignto(Integer assignto) {
		this.assignto = assignto;
	}

	public Date getExpecteddeliverydate() {
		return expecteddeliverydate;
	}

	public void setExpecteddeliverydate(Date expecteddeliverydate) {
		this.expecteddeliverydate = expecteddeliverydate;
	}

	public Integer getJobid() {
		return jobid;
	}

	public void setJobid(Integer jobid) {
		this.jobid = jobid;
	}

	public String getTasks() {
		return tasks;
	}

	public void setTasks(String tasks) {
		this.tasks = tasks;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public JobQuery getJobquery() {
		return jobquery;
	}

	public void setJobquery(JobQuery jobquery) {
		this.jobquery = jobquery;
	}

}
