package com.model.order.dto;

import java.util.Date;

// default package
// Generated 14 Aug, 2018 9:02:51 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Books generated by hbm2java
 */
public class BooksSalesReport implements java.io.Serializable {

    private String orderdate;
    private String centercode;
    private String title;
    private String author;
    private String quantity;
    private String price;
    private String narration;
    private String language;

    public BooksSalesReport() {}

    public BooksSalesReport(String orderdate, String centercode, String title, String author, String quantity, String price, String narration, String language) {
        this.orderdate = orderdate;
        this.centercode = centercode;
        this.title = title;
        this.author = author;
        this.quantity = quantity;
        this.price = price;
        this.title = title;
        this.quantity = quantity;
        this.narration = narration;
        this.language = language;
    }

	public String getOrderdate() {
		return orderdate;
	}

	public void setOrderdate(String orderdate) {
		this.orderdate = orderdate;
	}

	public String getCentercode() {
		return centercode;
	}

	public void setCentercode(String centercode) {
		this.centercode = centercode;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getQuantity() {
		return quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getNarration() {
		return narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

    

}
