package com.model.order.dto;

import java.util.Date;

// default package
// Generated 14 Aug, 2018 9:02:51 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

    private Integer id;
    private String isbn;
    private String language;
    private String author;
    private String publisher;
    private String bookimage;
    private String genre;
    private String title;
    private Integer quantity;
    private String edition;
    private Integer totalpage;
    private String description;
    private Integer userid;
    private Integer price;
    private Date purchaseddate;
    private Date createddate;

    public Books() {}

    public Books(String isbn, String language) {
        this.isbn = isbn;
        this.language = language;
    }

    public Books(String isbn, String language, String author, String publisher, String bookimage, String genre, String title,
            Integer quantity, String edition, Integer totalpage, String description, Integer userid, Integer price, Date purchaseddate, Date createddate) {
        this.isbn = isbn;
        this.language = language;
        this.author = author;
        this.publisher = publisher;
        this.bookimage = bookimage;
        this.genre = genre;
        this.title = title;
        this.quantity = quantity;
        this.edition = edition;
        this.totalpage = totalpage;
        this.description = description;
        this.userid = userid;
        this.price = price;
        this.purchaseddate = purchaseddate;
        this.createddate = createddate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublisher() {
        return this.publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getBookimage() {
        return this.bookimage;
    }

    public void setBookimage(String bookimage) {
        this.bookimage = bookimage;
    }

    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getEdition() {
        return this.edition;
    }

    public void setEdition(String edition) {
        this.edition = edition;
    }

    public Integer getTotalpage() {
        return this.totalpage;
    }

    public void setTotalpage(Integer totalpage) {
        this.totalpage = totalpage;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

	public Date getPurchaseddate() {
		return purchaseddate;
	}

	public void setPurchaseddate(Date purchaseddate) {
		this.purchaseddate = purchaseddate;
	}

	public Date getCreateddate() {
		return createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

}
