package com.model.order.dto;

// default package
// Generated 15 Aug, 2018 11:48:02 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Ordersdetails generated by hbm2java
 */
public class Ordersdetails implements java.io.Serializable {

    private Integer idordersdetails;
    private Integer bookid;
    private Integer quantity;
    private Integer orderssummaryid;

    public Ordersdetails() {}

    public Ordersdetails(Integer bookid, Integer quantity, Integer orderssummaryid) {
        this.bookid = bookid;
        this.quantity = quantity;
        this.orderssummaryid = orderssummaryid;
    }

    public Integer getIdordersdetails() {
        return this.idordersdetails;
    }

    public void setIdordersdetails(Integer idordersdetails) {
        this.idordersdetails = idordersdetails;
    }

    public Integer getBookid() {
        return this.bookid;
    }

    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    public Integer getOrderssummaryid() {
        return this.orderssummaryid;
    }

    public void setOrderssummaryid(Integer orderssummaryid) {
        this.orderssummaryid = orderssummaryid;
    }
}
