package com.model.order.dto;

// default package
// Generated 15 Aug, 2018 11:47:14 AM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Orderssummary generated by hbm2java
 */
public class Orderssummary implements java.io.Serializable {

    private Integer idorders;
    private String centercode;
    private Date orderdate;
    private Date confirmationdate;
    private String paymentstatus;
    private String narration;

    public Orderssummary() {}

    public Orderssummary(String centercode, Date orderdate, Date confirmationdate, String paymentstatus,
            String narration) {
        this.centercode = centercode;
        this.orderdate = orderdate;
        this.confirmationdate = confirmationdate;
        this.paymentstatus = paymentstatus;
        this.narration = narration;
    }

    public Integer getIdorders() {
        return this.idorders;
    }

    public void setIdorders(Integer idorders) {
        this.idorders = idorders;
    }

    public String getCentercode() {
        return this.centercode;
    }

    public void setCentercode(String centercode) {
        this.centercode = centercode;
    }

    public Date getOrderdate() {
        return this.orderdate;
    }

    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    public Date getConfirmationdate() {
        return this.confirmationdate;
    }

    public void setConfirmationdate(Date confirmationdate) {
        this.confirmationdate = confirmationdate;
    }

    public String getPaymentstatus() {
        return this.paymentstatus;
    }

    public void setPaymentstatus(String paymentstatus) {
        this.paymentstatus = paymentstatus;
    }

    public String getNarration() {
        return this.narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

}
