package org.ideoholic.curium.model.account.dto;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;

import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountgroupmaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "accountgroupid")
@Entity
@Table(name = "acc_accountgroupmaster")
public class Accountgroupmaster implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "accountgroupid", unique = true, nullable = false)
	private Integer accountgroupid;

	@Column(name = "accountgroupname", nullable = false, length = 150)
	private String accountgroupname;
	
	@JsonIgnore
    @OneToMany(mappedBy = "accountGroupMaster", fetch = FetchType.EAGER)
    private List<Accountsubgroupmaster> accountsubgroupmasterList;

    @JsonIgnore
	@OneToMany(mappedBy = "accountGroupMaster")
	private List<Accountdetails> accountdetailsList;
}