package org.ideoholic.curium.model.account.dto;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;

import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountdetails generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "accountdetailsid")
@Entity
@Table(name = "acc_accountdetails")
public class Accountdetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "accountdetailsid", unique = true, nullable = false)
	private Integer accountdetailsid;

	@Column(name = "accountname", nullable = false, length = 100)
	private String accountname;

	@Column(name = "accountcode", nullable = false, length = 100)
	private String accountcode;

	@ManyToOne
	@JoinColumn(name = "ssgroupmasterid", referencedColumnName = "ssgroupmasterid")
	private Accountssgroupmaster accountSSGroupMaster;

	@ManyToOne
	@JoinColumn(name = "accountsubgroupmasterid", referencedColumnName = "accountsubgroupmasterid")
	private Accountsubgroupmaster accountSubGroupMaster;

	@ManyToOne
	@JoinColumn(name = "accountgroupid")
	private Accountgroupmaster accountGroupMaster;
	
	@JsonIgnore
    @OneToMany(mappedBy = "accountDetails")
    private List<Accountdetailsbalance> accAccountdetailsbalanceList;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}