package org.ideoholic.curium.model.account.dto;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;

import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountsubgroupmaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "accountsubgroupmasterid")
@Entity
@Table(name = "acc_accountsubgroupmaster")
public class Accountsubgroupmaster implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "accountsubgroupmasterid", unique = true, nullable = false)
	private Integer accountsubgroupmasterid;

	@Column(name = "accountsubgroupname", length = 100)
	private String accountsubgroupname;

	//@Column(name = "accountgroupmasterid")
	//private Integer accountgroupid;

	@ManyToOne
	@JoinColumn(name = "accountgroupid")
	private Accountgroupmaster accountGroupMaster;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "accountSubGroupMaster")
	private List<Accountssgroupmaster> accAccountssubgroupmasterList;

	@JsonIgnore
	@OneToMany(mappedBy = "accountSubGroupMaster")
	private List<Accountdetails> accountdetailsList;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}