package org.ideoholic.curium.model.account.dto;

// default package
// Generated 18 Feb, 2018 10:47:48 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountdetailsbalance generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "accountdetailsbalanceid")
@Entity
@Table(name = "acc_accountdetailsbalance")
public class Accountdetailsbalance implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "accountdetailsbalanceid", unique = true, nullable = false)
	private Integer accountdetailsbalanceid;

	@Column(name = "openingbalance", precision = 20, scale = 4)
	private BigDecimal openingbalance;

	@Column(name = "currentbalance", precision = 20, scale = 4)
	private BigDecimal currentbalance;

	@ManyToOne
	@JoinColumn(name = "financialid", referencedColumnName = "financialid")
	private Financialaccountingyear financialAccountingYear;

	@Column(name = "crdr", length = 40)
	private String crdr;

	@Column(name = "enteredon")
	private Date enteredon;

	@ManyToOne
	@JoinColumn(name = "accountdetailsid")
	private Accountdetails accountDetails;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}