package org.ideoholic.curium.model.account.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 18 Feb, 2018 10:47:48 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountdetailsbalance generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "acc_accountdetailsbalance")
public class Accountdetailsbalance implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "accountdetailsbalanceid", unique = true, nullable = false)
	private Integer accountdetailsbalanceid;

	@Column(name = "accountdetailsid")
	private Integer accountdetailsid;

	@Column(name = "openingbalance", precision = 20, scale = 4)
	private BigDecimal openingbalance;

	@Column(name = "currentbalance", precision = 20, scale = 4)
	private BigDecimal currentbalance;

	@Column(name = "financialid")
	private Integer financialid;

	@Column(name = "crdr", length = 40)
	private String crdr;

	@Column(name = "enteredon")
	private Date enteredon;

	@ManyToOne
	@JoinColumn(name = "accountdetailsid")
	private Accountdetails accountDetails;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
