package org.ideoholic.curium.model.account.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountsubgroupmaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "acc_accountsubgroupmaster")
public class Accountsubgroupmaster implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "accountsubgroupmasterid", unique = true, nullable = false)
	private Integer accountsubgroupmasterid;

	@Column(name = "accountsubgroupname", length = 100)
	private String accountsubgroupname;

	@Column(name = "accountgroupmasterid")
	private Integer accountgroupid;

	@ManyToOne
	@JoinColumn(name = "accountgroupid")
	private Accountgroupmaster accountGroupMaster;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
