package org.ideoholic.curium.model.account.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountsubgroupmaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "acc_accountssubgroupmaster")
public class Accountssgroupmaster implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ssgroupmasterid", unique = true, nullable = false)
	private Integer ssgroupmasterid;

	@Column(name = "ssgroupname", length = 100)
	private String ssgroupname;

	@Column(name = "subgroupmasterid")
	private Integer subgroupmasterid;

	@ManyToOne
	@JoinColumn(name = "subgroupmasterid")
	private Accountsubgroupmaster accountSubGroupMaster;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
