package org.ideoholic.curium.model.account.dto;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;

import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Accountsubgroupmaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "ssgroupmasterid")
@Entity
@Table(name = "acc_accountssubgroupmaster")
public class Accountssgroupmaster implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ssgroupmasterid", unique = true, nullable = false)
	private Integer ssgroupmasterid;

	@Column(name = "ssgroupname", length = 100)
	private String ssgroupname;

	@ManyToOne
	@JoinColumn(name = "subgroupmasterid")
	private Accountsubgroupmaster accountSubGroupMaster;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	@JsonIgnore
	@OneToMany(mappedBy = "accountSSGroupMaster")
	private List<Accountdetails> accountdetailsList;

}