package org.ideoholic.curium.model.account.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 15 Feb, 2018 11:56:25 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Financialaccountingyear generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "acc_financialaccountingyear")
public class Financialaccountingyear implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "financialid", unique = true, nullable = false)
	private Integer financialid;

	@Temporal(TemporalType.DATE)
	@Column(name = "financialstartdate", nullable = false, length = 10)
	private Date financialstartdate;

	@Temporal(TemporalType.DATE)
	@Column(name = "financialenddate", nullable = false, length = 10)
	private Date financialenddate;

	@Column(name = "active", nullable = false, length = 10)
	private String active;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
