package org.ideoholic.curium.model.account.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 7 Mar, 2018 10:58:19 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * VoucherEntrytransactions generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "acc_voucherentrytransactions")
public class VoucherEntrytransactions implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transactionsid", unique = true, nullable = false)
	private Integer transactionsid;

	@Column(name = "draccountid")
	private Integer draccountid;

	@Column(name = "craccountid")
	private Integer craccountid;

	@Column(name = "dramount", precision = 10, scale = 5)
	private BigDecimal dramount;

	@Column(name = "cramount", precision = 10, scale = 5)
	private BigDecimal cramount;

	@Column(name = "vouchertype")
	private Integer vouchertype;

	@Temporal(TemporalType.DATE)
	@Column(name = "transactiondate", length = 10)
	private Date transactiondate;

	@Column(name = "entrydate", length = 10)
	private Date entrydate;

	@Column(name = "vouchercancellationdate", length = 10)
	private Date vouchercancellationdate;

	@Column(name = "narration", length = 500)
	private String narration;

	@Column(name = "financialyear")
	private int financialyear;

	@Column(name = "cancelvoucher", length = 5)
	private String cancelvoucher;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

	public int getFinancialyear() {
		return financialyear;
	}

	public void setFinancialyear(int financialyear) {
		this.financialyear = financialyear;
	}

	public String getCancelvoucher() {
		return cancelvoucher;
	}

	public void setCancelvoucher(String cancelvoucher) {
		this.cancelvoucher = cancelvoucher;
	}

	public Date getEntrydate() {
		return entrydate;
	}

	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}

	public Date getVouchercancellationdate() {
		return vouchercancellationdate;
	}

	public void setVouchercancellationdate(Date vouchercancellationdate) {
		this.vouchercancellationdate = vouchercancellationdate;
	}

	@Column(name = "branchid")
	public int getBranchid() {
		return branchid;
	}

	public void setBranchid(int branchid) {
		this.branchid = branchid;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
