package org.ideoholic.curium.model.std.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// default package
// Generated 29 Oct, 2018 4:21:55 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Classhierarchy generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "classhierarchy")
public class Classhierarchy implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idclasshierarchy")
	private Integer idclasshierarchy;

	@Column(name = "lowerclass", length = 45)
	private String lowerclass;

	@Column(name = "upperclass", length = 45)
	private String upperclass;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private int userid;

}
