package com.model.std.dto;

import java.util.HashSet;
import java.util.Set;

import com.model.feescollection.dto.Feescollection;

// default package
// Generated 29 Oct, 2018 4:21:55 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Classhierarchy generated by hbm2java
 */
public class Classhierarchy implements java.io.Serializable {

	private Integer idclasshierarchy;
	private String lowerclass;
	private String upperclass;
	private Integer branchid;
	private int userid;
	
	public Classhierarchy() {
	}

	public Classhierarchy(String lowerclass, String upperclass, Integer branchid, int userid) {
		this.lowerclass = lowerclass;
		this.upperclass = upperclass;
		this.branchid = branchid;
		this.userid = userid;
	}

	public Integer getIdclasshierarchy() {
		return this.idclasshierarchy;
	}

	public void setIdclasshierarchy(Integer idclasshierarchy) {
		this.idclasshierarchy = idclasshierarchy;
	}

	public String getLowerclass() {
		return this.lowerclass;
	}

	public void setLowerclass(String lowerclass) {
		this.lowerclass = lowerclass;
	}

	public String getUpperclass() {
		return this.upperclass;
	}

	public void setUpperclass(String upperclass) {
		this.upperclass = upperclass;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
