package com.model.std.dto;

// default package
// Generated 13 Aug, 2018 12:38:02 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Classhierarchy generated by hbm2java
 */
public class Classhierarchy implements java.io.Serializable {

    private Integer idclasshierarchy;
    private String lowerclass;
    private String upperclass;

    public Classhierarchy() {}

    public Classhierarchy(String lowerclass, String upperclass) {
        this.lowerclass = lowerclass;
        this.upperclass = upperclass;
    }

    public Integer getIdclasshierarchy() {
        return this.idclasshierarchy;
    }

    public void setIdclasshierarchy(Integer idclasshierarchy) {
        this.idclasshierarchy = idclasshierarchy;
    }

    public String getLowerclass() {
        return this.lowerclass;
    }

    public void setLowerclass(String lowerclass) {
        this.lowerclass = lowerclass;
    }

    public String getUpperclass() {
        return this.upperclass;
    }

    public void setUpperclass(String upperclass) {
        this.upperclass = upperclass;
    }

}
