package com.model.std.dto;

// default package
// Generated 6 Nov, 2014 12:17:14 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classsec generated by hbm2java
 */
@Entity
@Table(name = "classsec")
public class Classsec implements java.io.Serializable {

	private Integer stdrdid;
	private String classandsec;
	private int branchid;

	public Classsec() {
	}

	public Classsec(String classandsec, int branchid) {
		this.classandsec = classandsec;
		this.branchid = branchid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "stdrdid", unique = true, nullable = false)
	public Integer getStdrdid() {
		return this.stdrdid;
	}

	public void setStdrdid(Integer stdrdid) {
		this.stdrdid = stdrdid;
	}

	@Column(name = "classandsec", length = 45)
	public String getClassandsec() {
		return this.classandsec;
	}

	public void setClassandsec(String classandsec) {
		this.classandsec = classandsec;
	}

	
	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
}
