package com.model.examlevels.dto;

// default package
// Generated 21 Jul, 2018 3:09:11 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Examleveldetails generated by hbm2java
 */
public class Examleveldetails implements java.io.Serializable {

    private Integer idexamlevel;
    private String levelcode;
    private String levelname;
    private String duration;

    public Examleveldetails() {}

    public Examleveldetails(String levelcode, String levelname, String duration) {
        this.levelcode = levelcode;
        this.levelname = levelname;
        this.duration = duration;
    }

    public Integer getIdexamlevel() {
        return this.idexamlevel;
    }

    public void setIdexamlevel(Integer idexamlevel) {
        this.idexamlevel = idexamlevel;
    }

    public String getLevelcode() {
        return this.levelcode;
    }

    public void setLevelcode(String levelcode) {
        this.levelcode = levelcode;
    }

    public String getLevelname() {
        return this.levelname;
    }

    public void setLevelname(String levelname) {
        this.levelname = levelname;
    }

    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

}
