package com.model.examlevels.dto;

import java.util.HashSet;
import java.util.Set;

import com.model.subjectdetails.dto.Subject;

// default package
// Generated 30 Jul, 2018 5:07:45 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Subexamlevel generated by hbm2java
 */
public class Subexamlevel implements java.io.Serializable {

    private Integer idsubexamlevel;
    private String examlevel;
    private String subjectname;
    

    public Subexamlevel() {}

    public Subexamlevel(String examlevel, String subjectname) {
        this.examlevel = examlevel;
        this.subjectname = subjectname;
    }

    public Integer getIdsubexamlevel() {
        return this.idsubexamlevel;
    }

    public void setIdsubexamlevel(Integer idsubexamlevel) {
        this.idsubexamlevel = idsubexamlevel;
    }

    
    public String getExamlevel() {
        return this.examlevel;
    }

    
    public void setExamlevel(String examlevel) {
        this.examlevel = examlevel;
    }

    
    public String getSubjectname() {
        return this.subjectname;
    }

    
    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }


}
