package org.ideoholic.curium.model.mess.item.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * messItems generated by hbm2java
 */
@Entity
@Table(name = "mess_items")
public class MessItems implements java.io.Serializable {

	private Integer id;

	@Column(name = "externalid")
	private String externalid;

	@Column(name = "name")
	private String name;

	@Column(name = "unitofmeasure")
	private String unitofmeasure;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "linkedledgerid")
	private Integer linkedledgerid;

	@Column(name = "linkedledgeridexpense")
	private Integer linkedledgeridexpense;

	@Column(name = "userid")
	private int userid;

}
