package com.model.language.dto;

// default package
// Generated 22 Jul, 2018 12:47:39 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

    private Integer idlanguage;
    private String language;

    public Language() {}

    public Language(String language) {
        this.language = language;
    }

    public Integer getIdlanguage() {
        return this.idlanguage;
    }

    public void setIdlanguage(Integer idlanguage) {
        this.idlanguage = idlanguage;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

}
