package org.ideoholic.curium.model.employee.dto;

// default package
// Generated 20 Jan, 2018 9:49:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.ideoholic.curium.model.hr.dto.Leaveapplication;
import org.ideoholic.curium.model.hr.dto.Leavedetails;
import org.ideoholic.curium.model.hr.dto.Payadvancesalary;
import org.ideoholic.curium.model.hr.dto.Paybasic;
import org.ideoholic.curium.model.hr.dto.Payheadstaffdetails;
import org.ideoholic.curium.model.hr.dto.Processsalarydetails;
import org.ideoholic.curium.model.job.dto.JobQuery;
import org.ideoholic.curium.model.parents.dto.Parents;
import org.ideoholic.curium.model.task.dto.Task;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Teacher generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "teacher", uniqueConstraints = @UniqueConstraint(columnNames = "teacherexternalid"))
public class Teacher implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "tid", unique = true, nullable = false)
	private Integer tid;

	@Column(name = "teachername", nullable = false, length = 100)
	private String teachername;

	@Column(name = "designation", length = 45)
	private String designation;

	@Column(name = "subjectsteaching", length = 500)
	private String subjectsteaching;

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofjoining", length = 10)
	private Date dateofjoining;

	@Column(name = "classesteaching", length = 200)
	private String classesteaching;

	@Column(name = "salary", length = 50)
	private String salary;

	@Column(name = "department", length = 100)
	private String department;

	@Column(name = "qualification", length = 45)
	private String qualification;

	@Column(name = "totalexperience", length = 45)
	private String totalexperience;

	@Column(name = "address", length = 500)
	private String address;

	@Column(name = "contactnumber", length = 20)
	private String contactnumber;

	@Column(name = "email", length = 45)
	private String email;

	@Column(name = "remarks", length = 400)
	private String remarks;

	@Column(name = "gender", length = 45)
	private String gender;

	@Column(name = "teacherexternalid", unique = true, nullable = false, length = 45)
	private String teacherexternalid;

	@Temporal(TemporalType.DATE)
	@Column(name = "joiningdate")
	private Date joiningdate;

	@Temporal(TemporalType.DATE)
	@Column(name = "leavingdate")
	private Date leavingdate;

	@Column(name = "bankname", length = 500)
	private String bankname;

	@Column(name = "bankbranch", length = 200)
	private String bankbranch;

	@Column(name = "bankifsc", length = 50)
	private String bankifsc;

	@Column(name = "accno", length = 500)
	private String accno;

	@Column(name = "currentemployee", length = 20)
	private String currentemployee;

	@Lob
	@Column(name = "employeephoto", length = 2147483647)
	private String employeephoto;

	@Lob
	@Column(name = "employeedoc1", length = 2147483647)
	private String employeedoc1;

	@Lob
	@Column(name = "employeedoc2", length = 2147483647)
	private String employeedoc2;

	@Lob
	@Column(name = "employeedoc3", length = 2147483647)
	private String employeedoc3;

	@Lob
	@Column(name = "employeedoc4", length = 2147483647)
	private String employeedoc4;

	@Lob
	@Column(name = "employeedoc5", length = 2147483647)
	private String employeedoc5;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	@Column(name = "classteacher", length = 100)
    private String classteacher;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<JobQuery> jobList;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<Leavedetails> leavedetailsList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "teacher")
	private List<Payheadstaffdetails> payHeadDetailsList;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<Task> taskList;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<Processsalarydetails> salaryDetailsList;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<Leaveapplication> leaveApplicationList;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<Parents> parentsList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "teacher")
	private List<Paybasic> basicPayList;

	@JsonIgnore
	@OneToMany(mappedBy = "teacher")
	private List<Payadvancesalary> advanceSalaryList;

}
