package org.ideoholic.curium.model.employee.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 20 Jan, 2018 9:49:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Teacher generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "teacher", uniqueConstraints = @UniqueConstraint(columnNames = "teacherexternalid"))
public class Teacher implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tid", unique = true, nullable = false)
	private Integer tid;

	@Column(name = "teachername", nullable = false, length = 100)
	private String teachername;

	@Column(name = "designation", length = 45)
	private String designation;

	@Column(name = "subjectsteaching", length = 500)
	private String subjectsteaching;

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofjoining", length = 10)
	private Date dateofjoining;

	@Column(name = "classesteaching", length = 200)
	private String classesteaching;

	@Column(name = "salary", length = 50)
	private String salary;

	@Column(name = "department", length = 100)
	private String department;

	@Column(name = "qualification", length = 45)
	private String qualification;

	@Column(name = "totalexperience", length = 45)
	private String totalexperience;

	@Column(name = "address", length = 500)
	private String address;

	@Column(name = "contactnumber", length = 20)
	private String contactnumber;

	@Column(name = "email", length = 45)
	private String email;

	@Column(name = "remarks", length = 400)
	private String remarks;

	@Column(name = "gender", length = 45)
	private String gender;

	@Column(name = "teacherexternalid", unique = true, nullable = false, length = 45)
	private String teacherexternalid;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "leavingdate", length = 10)
	private Date leavingdate;

	@Column(name = "bankname", length = 500)
	private String bankname;

	@Column(name = "bankbranch", length = 200)
	private String bankbranch;

	@Column(name = "bankifsc", length = 50)
	private String bankifsc;

	@Column(name = "accno", length = 500)
	private String accno;

	@Column(name = "currentemployee", length = 20)
	private String currentemployee;

	@Column(name = "userid")
	private int userid;

}
