package org.ideoholic.curium.model.parents.dto;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.ideoholic.curium.model.appointment.dto.Appointment;
import org.ideoholic.curium.model.employee.dto.Teacher;
import org.ideoholic.curium.model.family.dto.Family;
import org.ideoholic.curium.model.family.dto.FamilyMember;
import org.ideoholic.curium.model.student.dto.Student;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Parents generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "parents")
public class Parents implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "pid", unique = true, nullable = false)
	private Integer pid;

	@Column(name = "fathersname", length = 100)
	private String fathersname;

	@Column(name = "mothersname", length = 100)
	private String mothersname;

	@Column(name = "addresspermanent", length = 500)
	private String addresspermanent;

	@Column(name = "addresstemporary", length = 500)
	private String addresstemporary;

	@Column(name = "professsion", length = 100)
	private String profession;

	@Column(name = "parentsannualincome", length = 100)
	private String parentsannualincome;

	@Column(name = "noofdependents")
	private Integer noofdependents;

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinColumn(name = "sid", referencedColumnName = "sid", unique = true, nullable = false)
	private Student student;

	@ManyToOne
	@JoinColumn(name = "tid", referencedColumnName = "tid")
	private Teacher teacher;

	@Column(name = "remarks", length = 500)
	private String remarks;

	@Column(name = "contactnumber", length = 50)
	private String cocontactnumber;

	@Column(name = "cocontactnumber", length = 50)
	private String contactnumber;

	@Column(name = "email", length = 45)
	private String email;

	@Column(name = "fathersqualification", length = 45)
	private String fathersqualification;

	@Column(name = "mothersqualification", length = 45)
	private String mothersqualification;

	@Column(name = "motherscastecertno", length = 100)
	private String motherscastecertno;

	@Column(name = "fatherscastecertno", length = 25)
	private String fatherscastecertno;

	@Column(name = "fatherscaste", length = 15)
	private String fatherscaste;

	@Column(name = "motherscaste", length = 15)
	private String motherscaste;

	@JsonIgnore
	@OneToMany(mappedBy = "parent")
	private List<Appointment> appointmentList;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;
	
	/**
	 * FamilyMember rows where this parent is a member.
	 * From these rows you can find the family and then the student members (offsprings).
	 */
	@JsonIgnore
	@OneToMany(mappedBy = "parent")
	private List<FamilyMember> familyMembers;

	/**
	 * Transient convenience list of offsprings (computed).
	 */
	@Transient
	private List<Student> offsprings;

	@Transient
	private String emergencycontactno;
	
	@Transient
	private String fatheroccupation;
	
	public Student fetchStudent() {
	      if(this.student != null) {
	            return student;
	       }
	       return new Student();
	}

	/**
	 * Compute offsprings (students) by traversing FamilyMember -> Family -> members.
	 * Removes duplicates and only returns Student members.
	 * For high-volume access prefer a direct JPQL query
	 */
	public List<Student> fetchOffspringsFromFamilies() {
		if (this.offsprings != null) {
			return this.offsprings;
		}
		if (this.familyMembers == null || this.familyMembers.isEmpty()) {
			return Collections.emptyList();
		}
		Set<Student> result = new LinkedHashSet<>();
		for (FamilyMember fm : this.familyMembers) {
			Family fam = fm.getFamily();
			if (fam == null || fam.getMembers() == null) {
				continue;
			}
			for (FamilyMember member : fam.getMembers()) {
				Student s = member.getStudent();
				if (s != null) {
					result.add(s);
				}
			}
		}
		this.offsprings = new ArrayList<>(result);
		return this.offsprings;
	}
}
