package org.ideoholic.curium.model.parents.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.student.dto.Student;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Parents generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "parents")
public class Parents implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pid", unique = true, nullable = false)
	private Integer pid;

	@Column(name = "fathersname", length = 100)
	private String fathersname;

	@Column(name = "mothersname", length = 100)
	private String mothersname;

	@Column(name = "addresspermanent", length = 500)
	private String addresspermanent;

	@Column(name = "addresstemporary", length = 500)
	private String addresstemporary;

	@Column(name = "professsion", length = 100)
	private String profession;

	@Column(name = "parentsannualincome")
	private String parentsannualincome;

	@Column(name = "noofdependents")
	private Integer noofdependents;

	@Column(name = "sid")
	private Integer sid;

	@Column(name = "tid")
	private Integer tid;

	@Column(name = "remarks")
	private String remarks;

	@Column(name = "cocontactnumber")
	private String contactnumber;

	@Column(name = "contactnumber")
	private String cocontactnumber;

	@Column(name = "email")
	private String email;

	@ManyToOne(cascade = CascadeType.ALL, fetch=FetchType.LAZY)
	@JoinColumn(name = "sid", unique=true, nullable = false)
	private Student student;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "fathersqualification")
	private String fathersqualification;

	@Column(name = "mothersqualification")
	private String mothersqualification;

	@Column(name = "motherscastecertno", length = 25)
	private String motherscastecertno;

	@Column(name = "fatherscastecertno", length = 25)
	private String fatherscastecertno;

	@Column(name = "fatherscaste", length = 25)
	private String fatherscaste;

	@Column(name = "motherscaste", length = 25)
	private String motherscaste;

	@Column(name = "userid")
	private int userid;

	private String emergencycontactno;
	private String fatheroccupation;

}
