package com.model.account.dto;

// default package
// Generated 16 Feb, 2018 11:27:48 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.model.feescollection.dto.Feescollection;

/**
 * Accountgroupmaster generated by hbm2java
 */
@Entity
@Table(name = "acc_accountgroupmaster")
public class Accountgroupmaster implements java.io.Serializable {

	private Integer accountgroupid;
	private String accountgroupname;
	
	
	public Accountgroupmaster() {
	}

	public Accountgroupmaster(String accountgroupname) {
		this.accountgroupname = accountgroupname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "accountgroupid", unique = true, nullable = false)
	public Integer getAccountgroupid() {
		return this.accountgroupid;
	}

	public void setAccountgroupid(Integer accountgroupid) {
		this.accountgroupid = accountgroupid;
	}

	@Column(name = "accountgroupname", nullable = false, length = 150)
	public String getAccountgroupname() {
		return this.accountgroupname;
	}

	public void setAccountgroupname(String accountgroupname) {
		this.accountgroupname = accountgroupname;
	}
}
