package com.model.account.dto;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Accountdetails generated by hbm2java
 */
@Entity
@Table(name = "acc_accountdetails")
public class Accountdetails implements java.io.Serializable {

	private Integer accountdetailsid;
	private int accountsubgroupmasterid;
	private int ssgroupmasterid;
	private int accountgroupid;
	private String accountname;
	private String accountcode;
	private Accountssgroupmaster accountSSGroupMaster;
	private Accountsubgroupmaster accountSubGroupMaster;
	private Accountgroupmaster accountGroupMaster;
	private int branchid;
	private int userid;
	
	public Accountdetails() {
	}

	public Accountdetails(int accountsubgroupmasterid, String accountname, Accountsubgroupmaster accountSubGroupMaster,
			int accountgroupid, Accountgroupmaster accountGroupMaster, int branchid, int userid, String accountcode, int ssgroupmasterid, Accountssgroupmaster accountSSGroupMaster) {
		this.accountsubgroupmasterid = accountsubgroupmasterid;
		this.accountname = accountname;
		this.accountSubGroupMaster = accountSubGroupMaster;
		this.accountgroupid = accountgroupid;
		this.accountGroupMaster = accountGroupMaster;
		this.branchid = branchid;
		this.accountcode = accountcode;
		this.ssgroupmasterid = ssgroupmasterid;
		this.accountSSGroupMaster = accountSSGroupMaster;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "accountdetailsid", unique = true, nullable = false)
	public Integer getAccountdetailsid() {
		return this.accountdetailsid;
	}

	public void setAccountdetailsid(Integer accountdetailsid) {
		this.accountdetailsid = accountdetailsid;
	}

	@Column(name = "accountsubgroupmasterid", nullable = false)
	public int getAccountsubgroupmasterid() {
		return this.accountsubgroupmasterid;
	}

	public void setAccountsubgroupmasterid(int accountsubgroupmasterid) {
		this.accountsubgroupmasterid = accountsubgroupmasterid;
	}
	
	@Column(name = "ssgroupmasterid", nullable = false)
	public int getSsgroupmasterid() {
		return ssgroupmasterid;
	}

	public void setSsgroupmasterid(int ssgroupmasterid) {
		this.ssgroupmasterid = ssgroupmasterid;
	}

	@Column(name = "accountname", nullable = false, length = 100)
	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	public Accountsubgroupmaster getAccountSubGroupMaster() {
		return accountSubGroupMaster;
	}

	public void setAccountSubGroupMaster(Accountsubgroupmaster accountSubGroupMaster) {
		this.accountSubGroupMaster = accountSubGroupMaster;
	}

	public int getAccountgroupid() {
		return accountgroupid;
	}

	public void setAccountgroupid(int accountgroupid) {
		this.accountgroupid = accountgroupid;
	}

	public Accountgroupmaster getAccountGroupMaster() {
		return accountGroupMaster;
	}

	public void setAccountGroupMaster(Accountgroupmaster accountGroupMaster) {
		this.accountGroupMaster = accountGroupMaster;
	}

	@Column(name = "branchid")
	public int getBranchid() {
		return branchid;
	}

	public void setBranchid(int branchid) {
		this.branchid = branchid;
	}

	public String getAccountcode() {
		return accountcode;
	}

	public void setAccountcode(String accountcode) {
		this.accountcode = accountcode;
	}

	public Accountssgroupmaster getAccountSSGroupMaster() {
		return accountSSGroupMaster;
	}

	public void setAccountSSGroupMaster(Accountssgroupmaster accountSSGroupMaster) {
		this.accountSSGroupMaster = accountSSGroupMaster;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
