package com.model.account.dto;

// default package
// Generated 18 Feb, 2018 10:47:48 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Accountdetailsbalance generated by hbm2java
 */
@Entity
@Table(name = "acc_accountdetailsbalance")
public class Accountdetailsbalance implements java.io.Serializable {

	private Integer accountdetailsbalanceid;
	private Integer accountdetailsid;
	private BigDecimal openingbalance;
	private BigDecimal currentbalance;
	private Integer financialid;
	private String crdr;
	private Date enteredon;
	private Accountdetails accountDetails;
	private int branchid;
	private int userid;

	public Accountdetailsbalance() {
	}

	public Accountdetailsbalance(Integer accountdetailsid, BigDecimal openingbalance,
			Integer financialid, String crdr, Accountdetails accountDetails, BigDecimal currentbalance, Date enteredon,
			int branchid, int userid) {
		this.accountdetailsid = accountdetailsid;
		this.openingbalance = openingbalance;
		this.financialid = financialid;
		this.crdr = crdr;
		this.accountDetails = accountDetails;
		this.currentbalance = currentbalance;
		this.enteredon = enteredon;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "accountdetailsbalanceid", unique = true, nullable = false)
	public Integer getAccountdetailsbalanceid() {
		return this.accountdetailsbalanceid;
	}

	public void setAccountdetailsbalanceid(Integer accountdetailsbalanceid) {
		this.accountdetailsbalanceid = accountdetailsbalanceid;
	}

	@Column(name = "accountdetailsid")
	public Integer getAccountdetailsid() {
		return this.accountdetailsid;
	}

	public void setAccountdetailsid(Integer accountdetailsid) {
		this.accountdetailsid = accountdetailsid;
	}

	@Column(name = "openingbalance", precision = 20, scale = 4)
	public BigDecimal getOpeningbalance() {
		return this.openingbalance;
	}

	public void setOpeningbalance(BigDecimal openingbalance) {
		this.openingbalance = openingbalance;
	}

	@Column(name = "financialid")
	public Integer getFinancialid() {
		return this.financialid;
	}

	public void setFinancialid(Integer financialid) {
		this.financialid = financialid;
	}

	@Column(name = "crdr", length = 40)
	public String getCrdr() {
		return this.crdr;
	}

	public void setCrdr(String crdr) {
		this.crdr = crdr;
	}

	public Accountdetails getAccountDetails() {
		return accountDetails;
	}

	public void setAccountDetails(Accountdetails accountDetails) {
		this.accountDetails = accountDetails;
	}

	public BigDecimal getCurrentbalance() {
		return currentbalance;
	}

	public void setCurrentbalance(BigDecimal currentbalance) {
		this.currentbalance = currentbalance;
	}

	public Date getEnteredon() {
		return enteredon;
	}

	public void setEnteredon(Date enteredon) {
		this.enteredon = enteredon;
	}

	@Column(name = "branchid")
	public int getBranchid() {
		return branchid;
	}

	public void setBranchid(int branchid) {
		this.branchid = branchid;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
