package org.ideoholic.curium.model.hr.dto;


import java.util.List;

// default package
// Generated 18 Apr, 2018 3:59:01 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Leavetypemaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_leavetypemaster")
public class Leavetypemaster implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idleavetypemaster", unique = true, nullable = false)
	private Integer idleavetypemaster;

	@Column(name = "leavetypename", length = 100)
	private String leavetypename;
	
    @OneToMany(mappedBy = "leaveTypeMaster")
    private List<Leavedetails> hrLeavedetailsList;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
