package org.ideoholic.curium.model.hr.dto;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.ideoholic.curium.model.employee.dto.Teacher;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payadvancesalary generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_payadvancesalary")
public class Payadvancesalary implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idpayadvancesalary", unique = true, nullable = false)
	private Integer idpayadvancesalary;

	@Column(name = "year", length = 45)
	private String year;

	@Column(name = "month", length = 45)
	private String month;

	@Column(name = "salaryfordays")
	private Integer salaryfordays;

	@Column(name = "deductionpermonth", precision = 20, scale = 4)
	private BigDecimal deductionpermonth;

	@Column(name = "amount", precision = 20, scale = 4)
	private BigDecimal amount;

	@Column(name = "deductionstartmonth", length = 45)
	private String deductionstartmonth;

	@Column(name = "deductionstartyear", length = 45)
	private String deductionstartyear;

	@Column(name = "status", length = 40)
	private String status;

	@ManyToOne
	@JoinColumn(name = "idteacher", referencedColumnName = "tid")
	private Teacher teacher;

	@Column(name = "reason", length = 500)
	private String reason;

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	private Date date;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
