package org.ideoholic.curium.model.hr.dto;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.employee.dto.Teacher;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Paybasic generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_paybasic")
public class Paybasic implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idpaybasic", unique = true, nullable = false)
	private Integer idpaybasic;

	@Column(name = "basicpay", precision = 20, scale = 4)
	private BigDecimal basicpay;

	@Column(name = "paymenttype", length = 45)
	private String paymenttype;

	@Column(name = "accountno", length = 40)
	private String accountno;

	@Column(name = "overtime", length = 10)
	private String overtime;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@ManyToOne
	@JoinColumn(name = "idteacher", referencedColumnName = "tid", nullable = false)
	private Teacher teacher;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
