package org.ideoholic.curium.model.hr.dto;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.employee.dto.Teacher;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payheadstaffdetails generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_payheadstaffdetails")
public class Payheadstaffdetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idpayheadstaffdetails", unique = true, nullable = false)
	private Integer idpayheadstaffdetails;

	@Column(name = "value", precision = 20, scale = 4)
	private BigDecimal value;

	@Column(name = "amountperc")
	private String amountperc;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@ManyToOne
	@JoinColumn(name = "idteacher", referencedColumnName = "tid", nullable = false)
	private Teacher teacher;

	@ManyToOne
	@JoinColumn(name = "payheadid", referencedColumnName = "idpayhead")
	private Payhead payhead;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
