package org.ideoholic.curium.model.hr.dto;

// default package
// Generated 22 Apr, 2018 5:13:05 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.employee.dto.Teacher;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payheadstaffdetails generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_payheadstaffdetails")
public class Payheadstaffdetails implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpayheadstaffdetails", unique = true, nullable = false)
	private Integer idpayheadstaffdetails;

	@Column(name = "idteacher", nullable = false)
	private int idteacher;

	@Column(name = "value", precision = 20, scale = 4)
	private BigDecimal value;

	@Column(name = "amountperc")
	private String amountperc;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@ManyToOne
	@JoinColumn(name = "idteacher")
	private Teacher teacher;

	@ManyToOne
	@JoinColumn(name = "payheadid")
	private Payhead payhead;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
