package org.ideoholic.curium.model.hr.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 21 Apr, 2018 3:19:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payhead generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "payhead", catalog = "school")
public class Payhead implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpayhead", unique = true, nullable = false)
	private Integer idpayhead;

	@Column(name = "payheadname", length = 200)
	private String payheadname;

	@Column(name = "payheadtype", length = 40)
	private String payheadtype;

	@Column(name = "validatory", length = 45)
	private String validatory;

	@Column(name = "description", length = 200)
	private String description;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
