package org.ideoholic.curium.model.hr.dto;

// default package
// Generated 30 Apr, 2018 6:08:33 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.ideoholic.curium.model.employee.dto.Teacher;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Processsalarydetails generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_processsalarydetails")
public class Processsalarydetails implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idprocesssalarydetails", unique = true, nullable = false)
	private Integer idprocesssalarydetails;

	@Column(name = "teacherid")
	private Integer teacherid;

	@Column(name = "month", length = 10)
	private String month;

	@Column(name = "year")
	private Integer year;

	@Column(name = "netpayment", precision = 20, scale = 0)
	private BigDecimal netpayment;

	@Column(name = "status", length = 45)
	private String status;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Temporal(TemporalType.DATE)
	@Column(name = "processeddate", length = 10)
	private Date processeddate;

	@Temporal(TemporalType.DATE)
	@Column(name = "issueddate", length = 10)
	private Date issueddate;

	@ManyToOne
	@JoinColumn(name = "idteacher")
	private Teacher teacher;

	@Column(name = "paymenttype", length = 20)
	private String paymenttype;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
