package org.ideoholic.curium.model.hr.dto;

// default package
// Generated 30 Apr, 2018 6:08:18 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Processsalarydetailsheads generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "hr_processsalarydetailsheads")
public class Processsalarydetailsheads implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idprocesssalarydetailsheads", unique = true, nullable = false)
	private Integer idprocesssalarydetailsheads;

	@Column(name = "payheadname", length = 45)
	private String payheadname;

	@Column(name = "payheadtype", length = 45)
	private String payheadtype;

	@Column(name = "amount", precision = 20, scale = 0)
	private BigDecimal amount;

	@ManyToOne
	@JoinColumn(name = "idprocesssalary", referencedColumnName = "idprocesssalarydetails")
	private Processsalarydetails processsalarydetails;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
