package org.ideoholic.curium.model.academicyear.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 8 May, 2015 5:04:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Currentacademicyear generated by hbm2java
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "currentacademicyear")
public class Currentacademicyear implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cayid", unique = true, nullable = false)
	private Integer cayid;

	@Column(name = "currentacademicyear", length = 100)
	private String currentacademicyear;

}
