package org.ideoholic.curium.model.appointment.dto;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.ideoholic.curium.model.parents.dto.Parents;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Branch generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "h_appointment")
public class Appointment implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "externalid", nullable = false, length = 100)
	private String externalid;

	@Temporal(TemporalType.DATE)
	@Column(name = "appointmentdate")
	private Date appointmentdate;

	@Column(name = "appointmenttime", length = 100)
	private String appointmenttime;

	@Column(name = "createduserid")
	private Integer createduserid;

	@Column(name = "updateduserid")
	private Integer updateduserid;

	@Temporal(TemporalType.DATE)
	@Column(name = "createddate")
	private Date createddate;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "academicyear", length = 20)
	private String academicyear;

	@Column(name = "status", length = 100)
	private String status;

	@Column(name = "appointmentstarttime", length = 100)
	private String appointmentstarttime;

	@Column(name = "appointmentendtime", length = 100)
	private String appointmentendtime;

	@Column(name = "totaltime", length = 100)
	private String totaltime;

	@ManyToOne
	@JoinColumn(name = "stdid", referencedColumnName = "pid")
	private Parents parent;

}
