package org.ideoholic.curium.model.appointment.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.ideoholic.curium.model.parents.dto.Parents;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "h_appointment")
public class Appointment implements java.io.Serializable {

	private Integer id;
	private Integer stdid;
	private String externalid;
	private Date appointmentdate;
	private String appointmenttime;
	private Integer createduserid;
	private Integer updateduserid;
	private Date createddate;
	private Integer branchid;
	private String academicyear;
	private String status;
	private Parents parent;
	private Integer userid;
	
	public Appointment() {
	}

	public Appointment(Integer stdid, String externalid, Date appointmentdate, String appointmenttime, Integer createduserid, Integer updateduserid, 
			Date createddate, Integer branchid, String academicyear, String status, Integer userid){
		this.stdid = stdid;
		this.externalid = externalid;
		this.appointmentdate = appointmentdate;
		this.appointmenttime = appointmenttime;
		this.createduserid = createduserid;
		this.updateduserid = updateduserid;
		this.createddate = createddate;
		this.branchid = branchid;
		this.academicyear = academicyear;
		this.status = status;
		this.userid = userid;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStdid() {
		return stdid;
	}

	public void setStdid(Integer stdid) {
		this.stdid = stdid;
	}

	public String getExternalid() {
		return externalid;
	}

	public void setExternalid(String externalid) {
		this.externalid = externalid;
	}

	public Date getAppointmentdate() {
		return appointmentdate;
	}

	public void setAppointmentdate(Date appointmentdate) {
		this.appointmentdate = appointmentdate;
	}

	public String getAppointmenttime() {
		return appointmenttime;
	}

	public void setAppointmenttime(String appointmenttime) {
		this.appointmenttime = appointmenttime;
	}

	public Integer getCreateduserid() {
		return createduserid;
	}

	public void setCreateduserid(Integer createduserid) {
		this.createduserid = createduserid;
	}

	public Integer getUpdateduserid() {
		return updateduserid;
	}

	public void setUpdateduserid(Integer updateduserid) {
		this.updateduserid = updateduserid;
	}

	public Date getCreateddate() {
		return createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}

	public String getAcademicyear() {
		return academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Parents getParent() {
		return parent;
	}

	public void setParent(Parents parent) {
		this.parent = parent;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	
}
