package org.ideoholic.curium.model.attendance.dto;

// default package
// Generated 31 Jan, 2018 9:02:38 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Staffdailyattendance generated by hbm2java
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "att_staffdailyattendance")
public class Staffdailyattendance implements java.io.Serializable {

	@Id
	@Column(name = "attendanceid", unique = true, nullable = false)
	private int attendanceid;

	@Column(name = "attendeeid", nullable = false, length = 45)
	private String attendeeid;

	@Column(name = "intime", length = 15)
	private String intime;

	@Column(name = "outtime", length = 15)
	private String outtime;

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	private Date date;

	@Column(name = "attendancestatus", length = 45)
	private String attendancestatus;

	@Column(name = "academicyear", length = 10)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
