package org.ideoholic.curium.model.attendance.dto;

// default package
// Generated 22 Jan, 2018 4:35:50 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.ideoholic.curium.model.student.dto.Student;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Studentdailyattendance generated by hbm2java
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "att_studentdailyattendance")
public class Studentdailyattendance implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "attendanceid", unique = true, nullable = false)
	private Integer attendanceid;

	@ManyToOne
	@JoinColumn(name = "attendeeid", referencedColumnName = "studentexternalid")
	private Student attendee;

	@Column(name = "intime", length = 45)
	private String intime;

	@Column(name = "outtime", length = 45)
	private String outtime;

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	private Date date;

	@Column(name = "attendancestatus", length = 15)
	private String attendancestatus;

	@Column(name = "academicyear", length = 10)
	private String academicyear;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	public Integer getAttendeeid() {
		if (attendee != null) {
			return attendee.getSid();
		}
		return 0;
	}

	public void setAttendeeid(String studentexternalid) {
		if (attendee == null) {
			attendee = new Student();
		}
		attendee.setStudentexternalid(studentexternalid);
	}

}
