package org.ideoholic.curium.model.attendance.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 22 Dec, 2017 4:15:19 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Weeklyoff generated by hbm2java
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "att_weeklyoff")
public class Weeklyoff implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "wid", unique = true, nullable = false)
	private Integer wid;

	@Column(name = "weeklyoffday", nullable = false, length = 100)
	private String weeklyoffday;

	@Column(name = "academicyear", length = 10)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
