// default package
// Generated 7 Apr, 2018 6:09:10 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Perioddetails generated by hbm2java
 */
@Entity
@Table(name = "perioddetails", catalog = "school")
public class Perioddetails implements java.io.Serializable {

	private Integer idperioddetails;
	private String periods;
	private String timings;
	private String days;

	public Perioddetails() {
	}

	public Perioddetails(String periods, String timings, String days) {
		this.periods = periods;
		this.timings = timings;
		this.days = days;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idperioddetails", unique = true, nullable = false)
	public Integer getIdperioddetails() {
		return this.idperioddetails;
	}

	public void setIdperioddetails(Integer idperioddetails) {
		this.idperioddetails = idperioddetails;
	}

	@Column(name = "periods", length = 45)
	public String getPeriods() {
		return this.periods;
	}

	public void setPeriods(String periods) {
		this.periods = periods;
	}

	@Column(name = "timings", length = 45)
	public String getTimings() {
		return this.timings;
	}

	public void setTimings(String timings) {
		this.timings = timings;
	}

	@Column(name = "days", length = 60)
	public String getDays() {
		return this.days;
	}

	public void setDays(String days) {
		this.days = days;
	}

}
