package org.ideoholic.curium.model.branch.dto;

// default package
// Generated 23 May, 2018 11:42:50 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch")
public class Branch implements java.io.Serializable {

	private Integer idbranch;
	private String branchname;
	private String branchcode;
	private String address;
	private String address1;
	private String address2;
	private String address3;
	private String address4;
	private String contact;

	public Branch() {
	}

	public Branch(String branchname, String branchcode, String address,String contact, String address1, String address2, String address3, String address4) {
		this.branchname = branchname;
		this.branchcode = branchcode;
		this.address = address;
		this.address = address1;
		this.address = address2;
		this.address = address3;
		this.address = address4;
		this.contact = contact;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idbranch", unique = true, nullable = false)
	public Integer getIdbranch() {
		return this.idbranch;
	}

	public void setIdbranch(Integer idbranch) {
		this.idbranch = idbranch;
	}

	@Column(name = "branchname", length = 50)
	public String getBranchname() {
		return this.branchname;
	}

	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}
	@Column(name = "branchcode", length = 50)
	public String getBranchcode() {
		return branchcode;
	}

	public void setBranchcode(String branchcode) {
		this.branchcode = branchcode;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public String getAddress4() {
		return address4;
	}

	public void setAddress4(String address4) {
		this.address4 = address4;
	}
}
