package org.ideoholic.curium.model.branch.dto;

import java.util.List;

// default package
// Generated 23 May, 2018 11:42:50 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.ideoholic.curium.model.user.dto.Login;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Branch generated by hbm2java
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "branch")
public class Branch implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idbranch", unique = true, nullable = false)
	private Integer idbranch;

	@Column(name = "branchname", length = 50)
	private String branchname;

	@Column(name = "branchcode", length = 50)
	private String branchcode;

	@Column(name = "address", length = 500)
	private String address;

	@Column(name = "contact", length = 200)
	private String contact;

	@OneToMany(mappedBy = "branch")
	private List<Login> loginList;
}
