package com.model.degreedetails.dto;

// default package
// Generated 5 Jul, 2018 7:53:04 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Degreedetails generated by hbm2java
 */
public class Degreedetails implements java.io.Serializable {

    private Integer iddegreedetails;
    private Integer exampassedappearance;
    private String exampassedyear;
    private String exampassedregno;
    private String exampassedresultwithclass;
    private String pumediuminstruction;
    private String subjectsqualifingexampartone;
    private String subjectsqualifingexamparttwo;
    private String subjectsdegreecoursepartone;
    private String subjectsdegreecourseparttwo;
    private Integer pumarkscard;
    private Integer medicalreport;
    private Integer incomecertificate;
    private Integer migrationcertificate;
    private Integer transfercertificate;
    private Integer castecertificate;
    private String proficiencysports;
    private String extracurricular;
    private String areyouemployee;
    private Integer karnataka;

    public Degreedetails() {}

    public Degreedetails(Integer exampassedappearance, String exampassedyear, String exampassedregno, String exampassedresultwithclass,
            String pumediuminstruction, String subjectsqualifingexampartone, String subjectsqualifingexamparttwo,
            String subjectsdegreecoursepartone, String subjectsdegreecourseparttwo, Integer pumarkscard, Integer medicalreport,
            Integer incomecertificate, Integer migrationcertificate, Integer transfercertificate, Integer castecertificate,
            String proficiencysports, String extracurricular, String areyouemployee, Integer karnataka) {
        this.exampassedappearance = exampassedappearance;
        this.exampassedyear = exampassedyear;
        this.exampassedregno = exampassedregno;
        this.exampassedresultwithclass = exampassedresultwithclass;
        this.pumediuminstruction = pumediuminstruction;
        this.subjectsqualifingexampartone = subjectsqualifingexampartone;
        this.subjectsqualifingexamparttwo = subjectsqualifingexamparttwo;
        this.subjectsdegreecoursepartone = subjectsdegreecoursepartone;
        this.subjectsdegreecourseparttwo = subjectsdegreecourseparttwo;
        this.pumarkscard = pumarkscard;
        this.medicalreport = medicalreport;
        this.incomecertificate = incomecertificate;
        this.migrationcertificate = migrationcertificate;
        this.transfercertificate = transfercertificate;
        this.castecertificate = castecertificate;
        this.proficiencysports = proficiencysports;
        this.extracurricular = extracurricular;
        this.areyouemployee = areyouemployee;
        this.karnataka = karnataka;
    }

    public Integer getIddegreedetails() {
        return this.iddegreedetails;
    }

    public void setIddegreedetails(Integer iddegreedetails) {
        this.iddegreedetails = iddegreedetails;
    }

    public Integer getExampassedappearance() {
        return this.exampassedappearance;
    }

    public void setExampassedappearance(Integer exampassedappearance) {
        this.exampassedappearance = exampassedappearance;
    }

    public String getExampassedyear() {
        return this.exampassedyear;
    }

    public void setExampassedyear(String exampassedyear) {
        this.exampassedyear = exampassedyear;
    }

    public String getExampassedregno() {
        return this.exampassedregno;
    }

    public void setExampassedregno(String exampassedregno) {
        this.exampassedregno = exampassedregno;
    }

    public String getExampassedresultwithclass() {
        return this.exampassedresultwithclass;
    }

    public void setExampassedresultwithclass(String exampassedresultwithclass) {
        this.exampassedresultwithclass = exampassedresultwithclass;
    }

    public String getPumediuminstruction() {
        return this.pumediuminstruction;
    }

    public void setPumediuminstruction(String pumediuminstruction) {
        this.pumediuminstruction = pumediuminstruction;
    }

    public String getSubjectsqualifingexampartone() {
        return this.subjectsqualifingexampartone;
    }

    public void setSubjectsqualifingexampartone(String subjectsqualifingexampartone) {
        this.subjectsqualifingexampartone = subjectsqualifingexampartone;
    }

    public String getSubjectsqualifingexamparttwo() {
        return this.subjectsqualifingexamparttwo;
    }

    public void setSubjectsqualifingexamparttwo(String subjectsqualifingexamparttwo) {
        this.subjectsqualifingexamparttwo = subjectsqualifingexamparttwo;
    }

    public String getSubjectsdegreecoursepartone() {
        return this.subjectsdegreecoursepartone;
    }

    public void setSubjectsdegreecoursepartone(String subjectsdegreecoursepartone) {
        this.subjectsdegreecoursepartone = subjectsdegreecoursepartone;
    }

    public String getSubjectsdegreecourseparttwo() {
        return this.subjectsdegreecourseparttwo;
    }

    public void setSubjectsdegreecourseparttwo(String subjectsdegreecourseparttwo) {
        this.subjectsdegreecourseparttwo = subjectsdegreecourseparttwo;
    }

    public Integer getPumarkscard() {
        return this.pumarkscard;
    }

    public void setPumarkscard(Integer pumarkscard) {
        this.pumarkscard = pumarkscard;
    }

    public Integer getMedicalreport() {
        return this.medicalreport;
    }

    public void setMedicalreport(Integer medicalreport) {
        this.medicalreport = medicalreport;
    }

    public Integer getIncomecertificate() {
        return this.incomecertificate;
    }

    public void setIncomecertificate(Integer incomecertificate) {
        this.incomecertificate = incomecertificate;
    }

    public Integer getMigrationcertificate() {
        return this.migrationcertificate;
    }

    public void setMigrationcertificate(Integer migrationcertificate) {
        this.migrationcertificate = migrationcertificate;
    }

    public Integer getTransfercertificate() {
        return this.transfercertificate;
    }

    public void setTransfercertificate(Integer transfercertificate) {
        this.transfercertificate = transfercertificate;
    }

    public Integer getCastecertificate() {
        return this.castecertificate;
    }

    public void setCastecertificate(Integer castecertificate) {
        this.castecertificate = castecertificate;
    }

    public String getProficiencysports() {
        return this.proficiencysports;
    }

    public void setProficiencysports(String proficiencysports) {
        this.proficiencysports = proficiencysports;
    }

    public String getExtracurricular() {
        return this.extracurricular;
    }

    public void setExtracurricular(String extracurricular) {
        this.extracurricular = extracurricular;
    }

    public String getAreyouemployee() {
        return this.areyouemployee;
    }

    public void setAreyouemployee(String areyouemployee) {
        this.areyouemployee = areyouemployee;
    }

    public Integer getKarnataka() {
        return this.karnataka;
    }

    public void setKarnataka(Integer karnataka) {
        this.karnataka = karnataka;
    }

}
