package com.model.academicyear.dto;

// default package
// Generated 8 May, 2015 5:04:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Currentacademicyear generated by hbm2java
 */
@Entity
@Table(name = "currentacademicyear")
public class Currentacademicyear implements java.io.Serializable {

	private Integer cayid;
	private String currentacademicyear;

	public Currentacademicyear() {
	}

	public Currentacademicyear(String currentacademicyear) {
		this.currentacademicyear = currentacademicyear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cayid", unique = true, nullable = false)
	public Integer getCayid() {
		return this.cayid;
	}

	public void setCayid(Integer cayid) {
		this.cayid = cayid;
	}

	@Column(name = "currentacademicyear", length = 100)
	public String getCurrentacademicyear() {
		return this.currentacademicyear;
	}

	public void setCurrentacademicyear(String currentacademicyear) {
		this.currentacademicyear = currentacademicyear;
	}

}
