package org.ideoholic.curium.model.degreedetails.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// default package
// Generated 5 Jul, 2018 7:53:04 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Degreedetails generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "degreedetails")
public class Degreedetails implements java.io.Serializable {

	@Column(name = "iddegreedetails")
	private Integer iddegreedetails;

	@Column(name = "exampassedappearance")
	private Integer exampassedappearance;

	@Column(name = "exampassedyear", length = 45)
	private String exampassedyear;

	@Column(name = "exampassedregno", length = 45)
	private String exampassedregno;

	@Column(name = "exampassedresultwithclass", length = 100)
	private String exampassedresultwithclass;

	@Column(name = "pumediuminstruction", length = 45)
	private String pumediuminstruction;

	@Column(name = "subjectsqualifingexampartone", length = 200)
	private String subjectsqualifingexampartone;

	@Column(name = "subjectsqualifingexamparttwo", length = 500)
	private String subjectsqualifingexamparttwo;

	@Column(name = "subjectsdegreecoursepartone", length = 200)
	private String subjectsdegreecoursepartone;

	@Column(name = "subjectsdegreecourseparttwo", length = 500)
	private String subjectsdegreecourseparttwo;

	@Column(name = "pumarkscard")
	private Integer pumarkscard;

	@Column(name = "medicalreport")
	private Integer medicalreport;

	@Column(name = "incomecertificate")
	private Integer incomecertificate;

	@Column(name = "migrationcertificate")
	private Integer migrationcertificate;

	@Column(name = "transfercertificate")
	private Integer transfercertificate;

	@Column(name = "castecertificate")
	private Integer castecertificate;

	@Column(name = "proficiencysports", length = 400)
	private String proficiencysports;

	@Column(name = "extracurricular", length = 400)
	private String extracurricular;

	@Column(name = "areyouemployee", length = 45)
	private String areyouemployee;

	@Column(name = "karnataka")
	private Integer karnataka;

}
