# To see all the apps: https://www.dropbox.com/developers/apps
# Dropbox API Credentials
APP_KEY="App_Key_From_Dropbox_Apps"
APP_SECRET="App_Secret_From_Dropbox_Apps"

##################################
# Paste this URL into your browser to get authentication code: https://www.dropbox.com/oauth2/authorize?client_id=App_Key_From_Dropbox_Apps&token_access_type=offline&response_type=code
##################################

AUTH_CODE="Authenticatoin_code"

##################################
# Open your terminal and run this command for refresh token:
# curl https://api.dropbox.com/oauth2/token \
#     -d code=Authenticatoin_code \
#     -d grant_type=authorization_code \
#     -u App_Key_From_Dropbox_Apps:App_Secret_From_Dropbox_Apps
##################################

REFRESH_TOKEN="Refresh_token"

# Default Paths
CURIUM_DEST_FOLDER="/CURIUM"



