package com.model.query.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.model.department.dto.Department;
import com.model.parents.dto.Parents;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "h_queries")
public class ParentQuery implements java.io.Serializable {

	private Integer id;
	private Integer stdid;
	private String externalid;
	private String query;
	private Integer departmentid;
	private String response;
	private Integer createduserid;
	private Integer updateduserid;
	private Date createddate;
	private Date updateddate;
	private Integer branchid;
	private String academicyear;
	private String status;
	private Parents parent;
	private Department department;
	private String feedback;
	
	public ParentQuery() {
	}

	public ParentQuery(Integer stdid, String externalid, String query, String response, Integer createduserid, Integer updateduserid, 
			Date createddate, Date updateddate, Integer branchid, String academicyear, String status, String feedback){
		this.stdid = stdid;
		this.externalid = externalid;
		this.query = query;
		this.response = response;
		this.createduserid = createduserid;
		this.updateduserid = updateduserid;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.branchid = branchid;
		this.academicyear = academicyear;
		this.status = status;
		this.feedback = feedback;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStdid() {
		return stdid;
	}

	public void setStdid(Integer stdid) {
		this.stdid = stdid;
	}

	public String getExternalid() {
		return externalid;
	}

	public void setExternalid(String externalid) {
		this.externalid = externalid;
	}

	public Integer getCreateduserid() {
		return createduserid;
	}

	public void setCreateduserid(Integer createduserid) {
		this.createduserid = createduserid;
	}

	public Integer getUpdateduserid() {
		return updateduserid;
	}

	public void setUpdateduserid(Integer updateduserid) {
		this.updateduserid = updateduserid;
	}

	public Date getCreateddate() {
		return createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}

	public String getAcademicyear() {
		return academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Parents getParent() {
		return parent;
	}

	public void setParent(Parents parent) {
		this.parent = parent;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public Integer getDepartmentid() {
		return departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public String getResponse() {
		return response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	public Date getUpdateddate() {
		return updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getFeedback() {
		return feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	
}
