package org.ideoholic.curium.model.documents.dto;

// default package
// Generated 21 Mar, 2018 9:55:30 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transfercertificate generated by hbm2java
 */
@Entity
@Table(name = "transfercertificate")
public class Transfercertificate implements java.io.Serializable {

	private Integer tcid;
	private String applicationstatus;
	private Integer noofissues;
	private Date dateofissues;
	private String generalconduct;
	private String progress;
	private Integer sid;
	private int branchid;
	private int userid;
	private Integer bookno;
	private String lastExam;
	private String schoolDuesPaid;
	private String concession;
	private String totalWorkingDays;
	private String totalDaysPresent;
	private String remarks;

	public Transfercertificate() {
	}

	public Transfercertificate(String applicationstatus, Integer noofissues,
			Date dateofissues, String generalconduct, String progress, Integer sid, int branchid, int userid, int bookno,
			String lastExam, String schoolDuesPaid, String concession, String totalWorkingDays, String totalDaysPresent,
			String remarks) {
		this.applicationstatus = applicationstatus;
		this.noofissues = noofissues;
		this.dateofissues = dateofissues;
		this.generalconduct = generalconduct;
		this.progress = progress;
		this.sid = sid;
		this.branchid = branchid;
		this.userid = userid;
		this.bookno = bookno;
		this.lastExam = lastExam;
		this.schoolDuesPaid = schoolDuesPaid;
		this.concession = concession;
		this.totalWorkingDays = totalWorkingDays;
		this.totalDaysPresent = totalDaysPresent;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tcid", unique = true, nullable = false)
	public Integer getTcid() {
		return this.tcid;
	}

	public void setTcid(Integer tcid) {
		this.tcid = tcid;
	}

	@Column(name = "applicationstatus", length = 20)
	public String getApplicationstatus() {
		return this.applicationstatus;
	}

	public void setApplicationstatus(String applicationstatus) {
		this.applicationstatus = applicationstatus;
	}

	@Column(name = "noofissues")
	public Integer getNoofissues() {
		return this.noofissues;
	}

	public void setNoofissues(Integer noofissues) {
		this.noofissues = noofissues;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofissues", length = 10)
	public Date getDateofissues() {
		return this.dateofissues;
	}

	public void setDateofissues(Date dateofissues) {
		this.dateofissues = dateofissues;
	}

	@Column(name = "generalconduct", length = 500)
	public String getGeneralconduct() {
		return this.generalconduct;
	}

	public void setGeneralconduct(String generalconduct) {
		this.generalconduct = generalconduct;
	}

	@Column(name = "progress", length = 100)
	public String getProgress() {
		return this.progress;
	}

	public void setProgress(String progress) {
		this.progress = progress;
	}

	@Column(name = "sid")
	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}
	
	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
	
	public int getUserid() {
			return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Integer getBookno() {
		return bookno;
	}

	public void setBookno(Integer bookno) {
		this.bookno = bookno;
	}

	@Column(name = "lastexam", length = 45)
	public String getLastExam() {
		return lastExam;
	}

	public void setLastExam(String lastExam) {
		this.lastExam = lastExam;
	}

	@Column(name = "schoolduespaid", length = 45)
	public String getSchoolDuesPaid() {
		return schoolDuesPaid;
	}

	public void setSchoolDuesPaid(String schoolDuesPaid) {
		this.schoolDuesPaid = schoolDuesPaid;
	}

	@Column(name = "concession", length = 45)
	public String getConcession() {
		return concession;
	}

	public void setConcession(String concession) {
		this.concession = concession;
	}

	@Column(name = "totalworkingdays", length = 45)
	public String getTotalWorkingDays() {
		return totalWorkingDays;
	}

	public void setTotalWorkingDays(String totalWorkingDays) {
		this.totalWorkingDays = totalWorkingDays;
	}

	@Column(name = "totaldayspresent", length = 45)
	public String getTotalDaysPresent() {
		return totalDaysPresent;
	}

	public void setTotalDaysPresent(String totalDaysPresent) {
		this.totalDaysPresent = totalDaysPresent;
	}

	@Column(name = "remarks", length = 45)
	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
}
