package org.ideoholic.curium.model.documents.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 21 Mar, 2018 9:55:30 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Transfercertificate generated by hbm2java
 */

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "transfercertificate")
public class Transfercertificate implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tcid", unique = true, nullable = false)
	private Integer tcid;

	@Column(name = "applicationstatus", length = 20)
	private String applicationstatus;

	@Column(name = "noofissues")
	private Integer noofissues;

	@Column(name = "dateofissues", length = 20)
	private String dateofissues;

	@Column(name = "generalconduct", length = 500)
	private String generalconduct;

	@Column(name = "progress", length = 100)
	private String progress;

	@Column(name = "sid")
	private Integer sid;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
