package org.ideoholic.curium.model.mess.stockmove.dto;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_stockmoves")
public class MessStockMove implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "externalid", nullable = false, length = 200)
	private String externalid;

	@Column(name = "quantity", precision = 12)
	private Float quantity;

	@Column(name = "purpose", length = 20)
	private String purpose;

	@Temporal(TemporalType.DATE)
	@Column(name = "transactiondate")
	private Date transactiondate;

	@Column(name = "issuedto", length = 300)
	private String issuedto;

	@Column(name = "itemid")
	private Integer itemid;

	@Column(name = "stockentryid")
	private Integer stockentryid;

	@Column(name = "status", length = 100)
	private String status;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
