package com.model.examdetails.dto;

// default package
// Generated 19 Aug, 2016 8:15:22 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exams generated by hbm2java
 */
@Entity
@Table(name = "exams")
public class Exams implements java.io.Serializable {

	private Integer exid;
	private String examname;
	private int branchid;
	private int userid;
	
	public Exams() {
	}

	public Exams(String examname, int branchid, int userid) {
		this.examname = examname;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exid", unique = true, nullable = false)
	public Integer getExid() {
		return this.exid;
	}

	public void setExid(Integer exid) {
		this.exid = exid;
	}

	@Column(name = "examname", length = 45)
	public String getExamname() {
		return this.examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
}
