package com.model.examdetails.dto;

// default package
// Generated 31 Mar, 2018 10:55:17 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examschedule generated by hbm2java
 */
@Entity
@Table(name = "examschedule")
public class Examschedule implements java.io.Serializable {

	private Integer idexamschedule;
	private Date date;
	private String starttime;
	private String endtime;
	private String subject;
	private String examname;
	private String classes;
	private String academicyear;
	private	int branchid;
	private int userid;
	
	public Examschedule() {
	}

	public Examschedule(Date date, String starttime, String endtime,
			String subject, String examname, String classes, String academicyear,
			int branchid, int userid) {
		this.date = date;
		this.starttime = starttime;
		this.endtime = endtime;
		this.subject = subject;
		this.examname = examname;
		this.classes = classes;
		this.academicyear = academicyear;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idexamschedule", unique = true, nullable = false)
	public Integer getIdexamschedule() {
		return this.idexamschedule;
	}

	public void setIdexamschedule(Integer idexamschedule) {
		this.idexamschedule = idexamschedule;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "starttime", length = 20)
	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	@Column(name = "endtime", length = 20)
	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	@Column(name = "subject", length = 30)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "examname", length = 30)
	public String getExamname() {
		return this.examname;
	}

	public void setExamname(String examname) {
		this.examname = examname;
	}

	@Column(name = "classes", length = 45)
	public String getClasses() {
		return this.classes;
	}

	public void setClasses(String classes) {
		this.classes = classes;
	}

	@Column(name = "academicyear", length = 45)
	public String getAcademicyear() {
		return this.academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}


	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
	
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}
	
}
