package org.ideoholic.curium.model.feescollection.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 5 Feb, 2018 11:54:01 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Feescollection generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "fee_feescollection")
public class Feescollection implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "feecollectionid", unique = true, nullable = false)
	private Integer feecollectionid;

	@Column(name = "sfsid", nullable = false)
	private int sfsid;

	@Column(name = "amountpaid", precision = 10, scale = 0)
	private Long amountpaid;

	@Column(name = "sid", nullable = false)
	private int sid;

	@Column(name = "fine", precision = 10, scale = 0)
	private Long fine;

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	private Date date;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "receiptnumber", nullable = false)
	private int receiptnumber;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
