package org.ideoholic.curium.model.periods.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 7 Apr, 2018 6:09:10 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Perioddetails generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "perioddetails")
public class Perioddetails implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idperioddetails", unique = true, nullable = false)
	private Integer idperioddetails;

	@Column(name = "periods", length = 45)
	private String periods;

	@Column(name = "periodmasterid")
	private Integer periodmasterid;

	@Column(name = "timings", length = 100)
	private String timings;

	@Column(name = "days", length = 60)
	private String days;

	@Column(name = "subject")
	private String subject;

	@Column(name = "staff")
	private String staff;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;
	
}
