package org.ideoholic.curium.model.periods.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 7 Apr, 2018 6:08:39 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Periodmaster generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "periodmaster")
public class Periodmaster implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idperiodmaster", unique = true, nullable = false)
	private Integer idperiodmaster;

	@Column(name = "class", length = 45)
	private String class_;

	@Column(name = "totalperiods")
	private Integer totalperiods;

	@Column(name = "totalbreaks")
	private Integer totalbreaks;

	@Column(name = "daystart", length = 45)
	private String daystart;

	@Column(name = "dayend", length = 45)
	private String dayend;

	@Column(name = "durationofperiod", length = 45)
	private String durationofperiod;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "Periodmaster")
	private Set<Perioddetails> periodDetails = new HashSet<Perioddetails>(0);

}
