package org.ideoholic.curium.model.stampfees.dto;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 12 May, 2015 11:31:40 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Academicfeesstructure generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "fee_academicfeesstructure")
public class Academicfeesstructure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "feesstructureid", unique = true, nullable = false)
	private Integer feesstructureid;

	@Column(name = "sid", nullable = false)
	private int sid;

	@Column(name = "totalfees", length = 45)
	private String totalfees;

	@Column(name = "paidfees", length = 45)
	private String paidfees;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
