package org.ideoholic.curium.model.marksdetails.dto;

// default package
// Generated 15 Aug, 2016 11:42:58 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.examdetails.dto.Exams;
import org.ideoholic.curium.model.student.dto.Student;
import org.ideoholic.curium.model.subjectdetails.dto.Subject;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Marks generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "marks")
public class Marks implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "marksid", unique = true, nullable = false)
	private Integer marksid;

	@Column(name = "marksobtained", precision = 12)
	private Float marksobtained;

	@Column(length = 100)
	private String subgrade;

	@ManyToOne
	@JoinColumn(name = "examid", referencedColumnName = "exid")
	private Exams exam;

	@ManyToOne
	@JoinColumn(name = "sid", referencedColumnName = "sid")
	private Student student;

	@ManyToOne
	@JoinColumn(name = "subid", referencedColumnName = "subid")
	private Subject subject;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "subsubjectid")
	private Integer subsubjectid;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	public Integer getSubid() {
		if (subject != null) {
			return subject.getSubid();
		}
		return null;
	}

	public int getExamid() {
		if (exam != null) {
			return exam.getExid();
		}
		return 0;
	}

}
