backupdirectory = 
mysqlpath = 
totalColumnNumber= 10
smsuser=
smspassword=
smssender=CURIUM
sendsms=yes
apikey=
absentmessagepreprimary=
absentmessageprimary=
absentmessagehigh=
classespreprimary=
classesprimary=
classeshigh=
HOSTNAME=smtp.gmail.com
SMTPPORT=465
USERNAME=
PASSWORD=
FROMADDRESS=

