package com.model.marksdetails.dto;

// default package
// Generated 15 Aug, 2016 11:42:58 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Marks generated by hbm2java
 */
@Entity
@Table(name = "marks")
public class Marks implements java.io.Serializable {

	private Integer marksid;
	private Integer sid;
	private Integer subid;
	private Integer examid;
	private Integer marksobtained;
	private String academicyear;
	private int branchid;
	private int userid;
	
	public Marks() {
	}

	public Marks(Integer sid, Integer subid, Integer examid,
			Integer marksobtained, String academicyear, int branchid, int userid) {
		this.sid = sid;
		this.subid = subid;
		this.examid = examid;
		this.marksobtained = marksobtained;
		this.academicyear = academicyear;
		this.branchid = branchid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "marksid", unique = true, nullable = false)
	public Integer getMarksid() {
		return this.marksid;
	}

	public void setMarksid(Integer marksid) {
		this.marksid = marksid;
	}

	@Column(name = "sid")
	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	@Column(name = "subid")
	public Integer getSubid() {
		return this.subid;
	}

	public void setSubid(Integer subid) {
		this.subid = subid;
	}

	@Column(name = "examid")
	public Integer getExamid() {
		return this.examid;
	}

	public void setExamid(Integer examid) {
		this.examid = examid;
	}

	@Column(name = "marksobtained")
	public Integer getMarksobtained() {
		return this.marksobtained;
	}

	public void setMarksobtained(Integer marksobtained) {
		this.marksobtained = marksobtained;
	}

	@Column(name = "academicyear")
	public String getAcademicyear() {
		return academicyear;
	}

	public void setAcademicyear(String academicyear) {
		this.academicyear = academicyear;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}
		
	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
