package com.model.mess.stockentry.dto;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

import com.model.mess.item.dto.MessItems;
import com.model.mess.supplier.dto.MessSuppliers;

/**
 * messItems generated by hbm2java
 */
@Entity
@Table(name = "mess_stockavailable")
public class MessStockAvailability implements java.io.Serializable {

	private Integer id;
	private Integer itemid;
	private Float availablestock;
	private Integer minstock;
	private Integer branchid;
	private MessItems messitems;
	
	public MessStockAvailability() {
	}
	
	public MessStockAvailability(Integer id, Float availablestock, Integer minstock,Integer branchid, Integer itemid) {
		this.id = id;
		this.availablestock = availablestock;
		this.minstock = minstock;
		this.branchid = branchid;
		this.itemid = itemid;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getItemid() {
		return itemid;
	}

	public void setItemid(Integer itemid) {
		this.itemid = itemid;
	}

	public Float getAvailablestock() {
		return availablestock;
	}

	public void setAvailablestock(Float availablestock) {
		this.availablestock = availablestock;
	}

	public Integer getMinstock() {
		return minstock;
	}

	public void setMinstock(Integer minstock) {
		this.minstock = minstock;
	}

	public Integer getBranchid() {
		return branchid;
	}

	public void setBranchid(Integer branchid) {
		this.branchid = branchid;
	}

	public MessItems getMessitems() {
		return messitems;
	}

	public void setMessitems(MessItems messitems) {
		this.messitems = messitems;
	}

	

}
