package com.model.employee.dto;

// default package
// Generated 13 Aug, 2018 3:12:45 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Organizersdetails generated by hbm2java
 */
public class Organizersdetails implements java.io.Serializable {

    private Integer idorganizersdetails;
    private String name;
    private String contactnumber;
    private String centercode;
    private String emailid;
    private String address;
    private String photo;

    public Organizersdetails() {}

    public Organizersdetails(String name, String contactnumber, String centercode, String emailid, String address, String photo) {
        this.name = name;
        this.contactnumber = contactnumber;
        this.centercode = centercode;
        this.emailid = emailid;
        this.address = address;
        this.photo = photo;
    }

    public Integer getIdorganizersdetails() {
        return this.idorganizersdetails;
    }

    public void setIdorganizersdetails(Integer idorganizersdetails) {
        this.idorganizersdetails = idorganizersdetails;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContactnumber() {
        return this.contactnumber;
    }

    public void setContactnumber(String contactnumber) {
        this.contactnumber = contactnumber;
    }

    public String getCentercode() {
        return this.centercode;
    }

    public void setCentercode(String centercode) {
        this.centercode = centercode;
    }

    public String getEmailid() {
        return this.emailid;
    }

    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

}
