package com.model.employee.dto;

// default package
// Generated 20 Jan, 2018 9:49:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", uniqueConstraints = @UniqueConstraint(columnNames = "teacherexternalid"))
public class Teacher implements java.io.Serializable {

	private Integer tid;
	private String teachername;
	private String designation;
	private String aadharnumber;
	private Date dateofjoining;
	private String pan;
	private String salary;
	private String department;
	private String qualification;
	private String totalexperience;
	private String address;
	private String contactnumber;
	private String email;
	private String remarks;
	private String gender;
	private String teacherexternalid;
	private int branchid;
	private Date leavingdate;
	private String bankname;
	private String bankbranch;
	private String bankifsc;
	private String accno;
	private String currentemployee;
	
	private String doc1;
	private String doc2;
	private String doc3;
	private String doc4;
	private String doc5;
	private String doc6;
	private String doc7;
	private String doc8;
	private String doc9;
	private String doc10;
	
	public Teacher() {
	}

	public Teacher(String teachername, String teacherexternalid) {
		this.teachername = teachername;
		this.teacherexternalid = teacherexternalid;
	}

	public Teacher(String teachername, String designation,
			String aadharnumber, Date dateofjoining,
			String pan, String salary, String department,
			String qualification, String totalexperience, String address,
			String contactnumber, String email, String remarks, String gender,
			String teacherexternalid, Date leavingdate, String bankname, String bankbranch, String bankifsc, String accno, String currentemployee,
			String doc1, String doc2, String doc3, String doc4, String doc5, String doc6, String doc7, String doc8, String doc9, String doc10) {
		this.teachername = teachername;
		this.designation = designation;
		this.aadharnumber = aadharnumber;
		this.dateofjoining = dateofjoining;
		this.pan = pan;
		this.salary = salary;
		this.department = department;
		this.qualification = qualification;
		this.totalexperience = totalexperience;
		this.address = address;
		this.contactnumber = contactnumber;
		this.email = email;
		this.remarks = remarks;
		this.gender = gender;
		this.teacherexternalid = teacherexternalid;
		this.leavingdate = leavingdate;
		this.bankname = bankname;
		this.bankbranch = bankbranch;
		this.bankifsc = bankifsc;
		this.accno = accno;
		this.currentemployee = currentemployee;
		this.doc1=doc1;
		this.doc2=doc2;
		this.doc3=doc3;
		this.doc4=doc4;
		this.doc5=doc5;
		this.doc6=doc7;
		this.doc8=doc8;
		this.doc9=doc9;
		this.doc10=doc10;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tid", unique = true, nullable = false)
	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	@Column(name = "teachername", nullable = false, length = 100)
	public String getTeachername() {
		return this.teachername;
	}

	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	@Column(name = "designation", length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "aadharnumber", length = 500)
	public String getAadharnumber() {
		return this.aadharnumber;
	}

	public void setAadharnumber(String aadharnumber) {
		this.aadharnumber = aadharnumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofjoining", length = 10)
	public Date getDateofjoining() {
		return this.dateofjoining;
	}

	public void setDateofjoining(Date dateofjoining) {
		this.dateofjoining = dateofjoining;
	}

	@Column(name = "pan", length = 200)
	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	@Column(name = "salary", length = 50)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "department", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "qualification", length = 45)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "totalexperience", length = 45)
	public String getTotalexperience() {
		return this.totalexperience;
	}

	public void setTotalexperience(String totalexperience) {
		this.totalexperience = totalexperience;
	}

	@Column(name = "address", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contactnumber", length = 20)
	public String getContactnumber() {
		return this.contactnumber;
	}

	public void setContactnumber(String contactnumber) {
		this.contactnumber = contactnumber;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "remarks", length = 400)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "teacherexternalid", unique = true, nullable = false, length = 45)
	public String getTeacherexternalid() {
		return this.teacherexternalid;
	}

	public void setTeacherexternalid(String teacherexternalid) {
		this.teacherexternalid = teacherexternalid;
	}

	@Column(name = "branchid")
	public int getBranchid() {
	return branchid;
	}

	public void setBranchid(int branchid) {
	this.branchid = branchid;
	}

	public Date getLeavingdate() {
		return leavingdate;
	}

	public void setLeavingdate(Date leavingdate) {
		this.leavingdate = leavingdate;
	}

	public String getBankname() {
		return bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	public String getBankbranch() {
		return bankbranch;
	}

	public void setBankbranch(String bankbranch) {
		this.bankbranch = bankbranch;
	}

	public String getBankifsc() {
		return bankifsc;
	}

	public void setBankifsc(String bankifsc) {
		this.bankifsc = bankifsc;
	}

	public String getAccno() {
		return accno;
	}

	public void setAccno(String accno) {
		this.accno = accno;
	}

	public String getCurrentemployee() {
		return currentemployee;
	}

	public void setCurrentemployee(String currentemployee) {
		this.currentemployee = currentemployee;
	}

	public String getDoc1() {
		return doc1;
	}

	public void setDoc1(String doc1) {
		this.doc1 = doc1;
	}

	public String getDoc2() {
		return doc2;
	}

	public void setDoc2(String doc2) {
		this.doc2 = doc2;
	}

	public String getDoc3() {
		return doc3;
	}

	public void setDoc3(String doc3) {
		this.doc3 = doc3;
	}

	public String getDoc4() {
		return doc4;
	}

	public void setDoc4(String doc4) {
		this.doc4 = doc4;
	}

	public String getDoc5() {
		return doc5;
	}

	public void setDoc5(String doc5) {
		this.doc5 = doc5;
	}

	public String getDoc6() {
		return doc6;
	}

	public void setDoc6(String doc6) {
		this.doc6 = doc6;
	}

	public String getDoc7() {
		return doc7;
	}

	public void setDoc7(String doc7) {
		this.doc7 = doc7;
	}

	public String getDoc8() {
		return doc8;
	}

	public void setDoc8(String doc8) {
		this.doc8 = doc8;
	}

	public String getDoc9() {
		return doc9;
	}

	public void setDoc9(String doc9) {
		this.doc9 = doc9;
	}

	public String getDoc10() {
		return doc10;
	}

	public void setDoc10(String doc10) {
		this.doc10 = doc10;
	}
}
