package org.ideoholic.curium.model.mess.supplier.dto;

import static javax.persistence.GenerationType.AUTO;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.ideoholic.curium.model.account.dto.Accountdetails;
import org.ideoholic.curium.model.mess.stockmove.dto.MessStockMove;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_suppliers")
public class MessSuppliers implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "externalid")
	private String externalid;
	
	@Column(name = "name")
	private String name;
	
	@Column(name = "contactnumber")
	private String contactnumber;
	
	@Column(name = "address")
	private String address;
	
	@Column(name = "bankaccountno")
	private String bankaccountno;
	
	@Column(name = "ifsccode")
	private String ifsccode;
	
	@Column(name = "payto")
	private String payto;
	
	@Column(name = "branchid")
	private Integer branchid;
	
	@Column(name = "linkedledgerid")
	private Integer linkedledgerid;
	
	@Column(name = "userid")
	private int userid;
	
	private boolean success;
}
