package org.ideoholic.curium.model.mess.supplier.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_suppliers")
public class MessSuppliers implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "externalid", length = 110)
	private String externalid;

	@Column(name = "name", length = 100)
	private String name;

	@Column(name = "contactnumber", length = 12)
	private String contactnumber;

	@Column(name = "address", length = 200)
	private String address;

	@Column(name = "bankaccountno", length = 100)
	private String bankaccountno;

	@Column(name = "ifsccode", length = 20)
	private String ifsccode;

	@Column(name = "payto", length = 200)
	private String payto;

	@Column(name = "linkedledgerid")
	private Integer linkedledgerid;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

}
