package org.ideoholic.curium.model.mess.supplier.dto;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * messItems generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "mess_supplierpaymentdetails")
public class MessSuppliersPayment implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "externalid", length = 100)
	private String externalid;

	@Column(name = "supplierid")
	private Integer supplierid;

	@Column(name = "chequeno", length = 100)
	private String chequeno;

	@Column(name = "amount", precision = 18, scale = 5)
	private Float amount;

	@Column(name = "voucherid")
	private Integer voucherid;

	@Column(name = "voucheridcleared")
	private Integer voucheridcleared;

	@Temporal(TemporalType.DATE)
	@Column(name = "issuedate")
	private Date issuedate;

	@Temporal(TemporalType.DATE)
	@Column(name = "delivereddate")
	private Date delivereddate;

	@Temporal(TemporalType.DATE)
	@Column(name = "cleareddate")
	private Date cleareddate;

	@Column(name = "status", length = 50)
	private String status;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "entrydate")
	private Date entrydate;

	@Column(name = "userid")
	private int userid;

}
