package org.ideoholic.curium.model.student.dto;

import java.util.List;

import javax.persistence.CascadeType;

// default package
// Generated 24 Jul, 2015 12:41:34 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.ideoholic.curium.model.feescategory.dto.Feescategory;
import org.ideoholic.curium.model.feescollection.dto.Feescollection;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Studentfeesstructure generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "fee_studentfeesstructure")
public class Studentfeesstructure implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sfsid", unique = true, nullable = false)
	private Integer sfsid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sid", referencedColumnName = "sid", nullable = false)
	private Student student;

	@Column(name = "feesamount", precision = 10, scale = 0)
	private Long feesamount;

	@Column(name = "feespaid", precision = 10, scale = 0)
	private Long feespaid;

	@Column(name = "concession")
	private Integer concession;

	@Column(name = "waiveoff", precision = 10, scale = 0)
	private Long waiveoff;

	@Column(name = "totalinstallment")
	private Integer totalinstallment;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfeescategory", referencedColumnName = "idfeescategory")
	private Feescategory feescategory;
	
	@Column(name = "concessionnotes", length = 200)
	private String concessionnotes;

    @Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "branchid")
	private Integer branchid;
	
	@Column(name = "userid")
	private Integer userid;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "studentFeeStructure")
    private List<Feescollection> feeFeescollectionList;

	public int fetchSid() {
		if (student != null) {
			return student.getSid();
		}
		return 0;
	}

	public int fetchIdfeescategory() {
		if (feescategory != null) {
			return feescategory.getIdfeescategory();
		}
		return 0;
	}
}
