package org.ideoholic.curium.model.student.dto;

// default package
// Generated 14 Feb, 2018 12:05:32 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.ideoholic.curium.model.attendance.dto.Studentdailyattendance;
import org.ideoholic.curium.model.degreedetails.dto.Degreedetails;
import org.ideoholic.curium.model.feescollection.dto.Feescollection;
import org.ideoholic.curium.model.feescollection.dto.Otherfeescollection;
import org.ideoholic.curium.model.feescollection.dto.Otherreceiptinfo;
import org.ideoholic.curium.model.feescollection.dto.Receiptinfo;
import org.ideoholic.curium.model.feesdetails.dto.Feesdetails;
import org.ideoholic.curium.model.marksdetails.dto.ExamRank;
import org.ideoholic.curium.model.marksdetails.dto.Marks;
import org.ideoholic.curium.model.parents.dto.Parents;
import org.ideoholic.curium.model.pudetails.dto.Pudetails;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Student generated by hbm2java
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "student", uniqueConstraints = @UniqueConstraint(columnNames = "studentexternalid"))
public class Student implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sid", unique = true, nullable = false)
	private Integer sid;

	@Column(name = "name", nullable = false, length = 200)
	private String name;

	@Column(name = "classstudying", length = 45)
	private String classstudying;

	@Column(name = "classadmittedin", length = 45)
	private String classadmittedin;

	@Column(name = "age")
	private Integer age;

	@Column(name = "gender", length = 45)
	private String gender;

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 10)
	private Date dateofbirth;

	@Column(name = "bloodgroup", length = 45)
	private String bloodgroup;

	@Column(name = "nationality", length = 45)
	private String nationality;

	@Column(name = "religion", length = 45)
	private String religion;

	@Column(name = "caste", length = 45)
	private String caste;

	@Temporal(TemporalType.DATE)
	@Column(name = "admissiondate", length = 10)
	private Date admissiondate;

	@Column(name = "admissionnumber", length = 20)
	private String admissionnumber;

	@Column(name = "mothertongue", length = 45)
	private String mothertongue;

	@Column(name = "Remarks", length = 500)
	private String remarks;

	@Column(name = "schoollastattended", length = 100)
	private String schoollastattended;

	@Column(name = "stdlaststudied", length = 45)
	private String stdlaststudied;

	@Builder.Default
	@Temporal(TemporalType.DATE)
	@Column(name = "createddate", length = 10)
	private Date createddate = new Date();

	@Lob
	@Column(name = "studentpic", length = 2147483647)
	private String studentpic;

	@Column(name = "studentexternalid", unique = true, nullable = false, length = 45)
	private String studentexternalid;

	@Column(name = "crecord", length = 45)
	private String crecord;

	@Temporal(TemporalType.DATE)
	@Column(name = "crecorddate", length = 10)
	private Date crecorddate;

	@Column(name = "placeofbirth", length = 100)
	private String placeofbirth;

	@Column(name = "nooftc")
	private Integer nooftc;

	@Temporal(TemporalType.DATE)
	@Column(name = "dateoftc", length = 10)
	private Date dateoftc;

	@Column(name = "classonleaving", length = 45)
	private String classonleaving;

	@Temporal(TemporalType.DATE)
	@Column(name = "dateleaving", length = 10)
	private Date dateleaving;

	@Column(name = "reasonleaving", length = 500)
	private String reasonleaving;

	@Column(name = "notcissued")
	private Integer notcissued;

	@Temporal(TemporalType.DATE)
	@Column(name = "datetcissued", length = 10)
	private Date datetcissued;

	@Column(name = "guardiandetails", length = 200)
	private String guardiandetails;

	@Column(name = "subsequentprogress", length = 500)
	private String subsequentprogress;

	@Column(name = "languagesstudied", length = 80)
	private String languagesstudied;

	@Column(name = "instructionmediumlastschool", length = 45)
	private String instructionmediumlastschool;

	@Builder.Default
	@Column(name = "archive")
	private Integer archive = 0;

	@Builder.Default
	@Column(name = "passedout")
	private Integer passedout = 0;

	@Builder.Default
	@Column(name = "droppedout")
	private Integer droppedout = 0;

	@Builder.Default
	@Column(name = "leftout")
	private Integer leftout = 0;

	@Column(name = "semester")
	private Integer semester;

	@Column(name = "stream", length = 25)
	private String stream;

	@Column(name = "mediumofinstruction", length = 15)
	private String mediumofinstruction;

	@Column(name = "previousschooltype", length = 30)
	private String previousschooltype;

	@Column(name = "previouschooladdress", length = 250)
	private String previouschooladdress;

	@Column(name = "urbanrural", length = 5)
	private String urbanrural;

	@Column(name = "studentscastecertno", length = 25)
	private String studentscastecertno;

	@Column(name = "studentscaste", length = 45)
	private String studentscaste;

	@Column(name = "socialcategory", length = 10)
	private String socialcategory;

	@Column(name = "belongtobpl")
	private Integer belongtobpl;

	@Column(name = "bplcardno", length = 25)
	private String bplcardno;

	@Column(name = "bhagyalakshmibondnumber", length = 25)
	private String bhagyalakshmibondnumber;

	@Column(name = "disabilitychild", length = 40)
	private String disabilitychild;

	@Column(name = "sts", length = 30)
	private String sts;

	@Column(name = "specialcategory", length = 25)
	private String specialcategory;

	@Column(name = "rte")
	private Integer rte;

	@Column(name = "bankname", length = 500)
	private String bankname;

	@Column(name = "bankbranch", length = 200)
	private String bankbranch;

	@Column(name = "accno", length = 50)
	private String accno;

	@Column(name = "bankifsc", length = 50)
	private String bankifsc;

	@Lob
	@Column(name = "studentdoc1", length = 2147483647)
	private String studentdoc1;

	@Lob
	@Column(name = "studentdoc2", length = 2147483647)
	private String studentdoc2;

	@Lob
	@Column(name = "studentdoc3", length = 2147483647)
	private String studentdoc3;

	@Lob
	@Column(name = "studentdoc4", length = 2147483647)
	private String studentdoc4;

	@Lob
	@Column(name = "studentdoc5", length = 2147483647)
	private String studentdoc5;

	@Column(name = "branchid")
	private Integer branchid;

	@Column(name = "userid")
	private Integer userid;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "pudetailsid", referencedColumnName = "idpudetails")
	private Pudetails pudetails;

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "degreedetailsid", referencedColumnName = "iddegreedetails")
	private Degreedetails degreedetails;

	@Column(name = "yearofadmission", length = 10)
	private String yearofadmission;

	@Column(name = "promotedyear", length = 10)
	private String promotedyear;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "attendee")
	private List<Studentdailyattendance> studentDailyAttendanceList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
	private List<Studentotherfeesstructure> studentFeesStructureList;

	@JsonIgnore
	@OneToMany(mappedBy = "student")
	private List<Feesdetails> feeFeesDetailsList;

	@JsonIgnore
	@OneToMany(mappedBy = "student")
	private List<ExamRank> examRankList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
	private List<Studentfeesstructure> feeStudentFeesStructureList;

	@JsonIgnore
	@OneToMany(mappedBy = "student")
	private List<Parents> parents;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
	private List<Feescollection> feesCollectionList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
	private List<Otherfeescollection> otherFeesCollectionList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
	private List<Receiptinfo> receiptInfoList;

	@JsonIgnore
	@OneToMany(mappedBy = "student")
	private List<Marks> marksList;

	@JsonIgnore
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "student")
	private List<Otherreceiptinfo> otherreceiptinfoList;

	@Transient
	private String lastcourse;
	
	@Transient
	private Integer totalmarks;
	
	@Transient
	private String lastfirstlanguage;
	
	@Transient
	private String lastsecondlanguage;
	
	@Transient
	private String lastschooladdress;
	
	@Transient
	private String registrationnumber;

	public int fetchAge() {
		if (age == null) {
			return 0;
		}
		return age;
	}
}