package org.ideoholic.curium.model.feesdetails.dto;

// default package
// Generated 11 Feb, 2015 9:12:09 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.ideoholic.curium.model.student.dto.Student;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Feesdetails generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "fee_feesdetails")
public class Feesdetails implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "feesdetailsid", unique = true, nullable = false)
	private Integer feesdetailsid;

	@ManyToOne
	@JoinColumn(name = "sid", referencedColumnName = "sid")
	private Student student;

	@Column(name = "dateoffees", length = 100)
	private String dateoffees;

	@Column(name = "grandtotal", length = 45)
	private String grandtotal;

	@Column(name = "miscamount", length = 45)
	private String miscamount;

	@Column(name = "balamount", length = 45)
	private String balamount;

	@Column(name = "amountpercat", length = 45)
	private String amountpercat;

	@Column(name = "academicyear", length = 45)
	private String academicyear;

	@Column(name = "branchid")
	private int branchid;

	@Column(name = "userid")
	private int userid;

}
